# Stage 5 -- Interpretability and label robustness (E5, E6)
(1) Compares the LGC co-occurrence adjacency and the LAT label-label attention against
the empirical co-occurrence matrix (Spearman correlation + heatmaps).
(2) Label-noise robustness using the per-tool predictions: evaluation on the uncontested
subset and re-training on majority-vote labels.
**Accelerator: GPU.** **Attach:** `scvd-lib`, `dive-smart-contracts`, `scvd-stage1-eda`,
`scvd-stage3-deep` (test predictions).

In [1]:
import os, sys, json, time
import numpy as np, pandas as pd
LIB = '/kaggle/input/datasets/smnihalahmed/scvd-lib'
if not os.path.isdir(LIB):
    LIB = os.environ.get('SCVD_LIB', os.path.abspath('..'))   # local fallback
sys.path.insert(0, LIB)
import scvd
root, log = scvd.setup_stage('stage5_interpretability')
SEEDS = (0,) if scvd.quick() else scvd.RNG_SEEDS
log.info('seeds=%s quick=%s', SEEDS, scvd.quick())

2026-09-25 18:30:04,696 INFO stage stage5_interpretability initialised at /kaggle/working/stage5_interpretability
2026-09-25 18:30:04,697 INFO seeds=(0, 1, 2) quick=False

In [2]:
pre, post, lab, tools = scvd.load_dive(log)
fam = scvd.family_columns(pre, post)
for k, v in fam.items():
    log.info('family %-18s %3d features', k, len(v))
for v in scvd.VIEWS:
    log.info('view F_%-4s %3d features', v, len(scvd.view_columns(fam, v)))

2026-09-25 18:30:29,418 INFO loaded DIVE: pre=(22330, 222) post=(22330, 177) labels=(22330, 9) tools=(26071, 49)
2026-09-25 18:30:29,420 INFO family code_metadata        6 features
2026-09-25 18:30:29,421 INFO family interface_source    46 features
2026-09-25 18:30:29,422 INFO family creation_opcodes   168 features
2026-09-25 18:30:29,423 INFO family tx_metadata         10 features
2026-09-25 18:30:29,423 INFO family temporal_position    8 features
2026-09-25 18:30:29,425 INFO family runtime_opcodes    158 features
2026-09-25 18:30:29,426 INFO view F_pre  220 features
2026-09-25 18:30:29,427 INFO view F_post 176 features
2026-09-25 18:30:29,428 INFO view F_all  396 features

In [3]:
splits, sdf = scvd.load_splits() or (scvd.build_splits(pre, lab, 0), None)
d = scvd.make_data(pre, post, lab, fam, 'all', *splits['S1'])
M = scvd.cooccurrence(d['y_tr'])
cfg = {'lr': 1e-3, 'dm': 128, 'layers': 3, 'tau': 0.2, 'batch': 256,
       'epochs': 60 if scvd.quick() else 120}
from scipy.stats import spearmanr
off = ~np.eye(8, dtype=bool)

# R2#5/#8 follow-up: this was a single un-varied run (SEEDS[0] only) -- GPU/cuDNN
# non-determinism means even a "fixed" seed gives a different trained model each
# time, so a single point estimate for the headline rho isn't defensible. Loop
# over all 3 seeds and report mean/range, same treatment as the robustness cell.
dep_rows = []
A_last = attn_last = None
for seed in SEEDS:
    scvd.set_seed(seed)
    lgc = scvd.LGC(d['fams'], M, dm=128, tau=0.2)
    _, _h = scvd.train_torch(lgc, d, cfg, log)
    A = scvd.lgc_A(M, 0.2)
    scvd.set_seed(seed)
    lat = scvd.LAT(d['fams'], dm=128, layers=3)
    _, _h = scvd.train_torch(lat, d, cfg, log)
    attn = scvd.extract_label_attention(lat, d)
    rho_lgc = spearmanr(M[off], A[off]).statistic
    rho_lat = spearmanr(M[off], attn[off]).statistic
    dep_rows.append({'seed': seed, 'rho_lgc': rho_lgc, 'rho_lat': rho_lat})
    log.info('seed%d: Spearman(M, A_lgc)=%.3f  Spearman(M, attn_lat)=%.3f', seed, rho_lgc, rho_lat)
    A_last, attn_last = A, attn   # keep one trained pair around for the pairwise CSV/plot below

dep_df = pd.DataFrame(dep_rows)
dep_df.to_csv(f'{root}/results/stage5_dependency_rho_by_seed.csv', index=False)
log.info('rho_lgc: mean=%.3f range=[%.3f,%.3f] | rho_lat: mean=%.3f range=[%.3f,%.3f]',
          dep_df['rho_lgc'].mean(), dep_df['rho_lgc'].min(), dep_df['rho_lgc'].max(),
          dep_df['rho_lat'].mean(), dep_df['rho_lat'].min(), dep_df['rho_lat'].max())

# per-pair CSV and plot still use one representative (last-seed) trained pair, as before
pd.DataFrame({'pair': [f'{scvd.LABEL_SHORT[i]}-{scvd.LABEL_SHORT[j]}'
                       for i in range(8) for j in range(8) if off[i, j]],
              'M': M[off], 'A_lgc': A_last[off], 'attn_lat': attn_last[off]}).to_csv(
    f'{root}/results/stage5_dependency_pairs.csv', index=False)
scvd.plot_dependency_maps(M, A_last, attn_last, root, log)

2026-09-25 18:30:52,214 INFO   ep 000 loss 2.4017 val_macro_f1 0.3842 *
2026-09-25 18:30:52,628 INFO   ep 001 loss 1.5038 val_macro_f1 0.3907 *
2026-09-25 18:30:53,005 INFO   ep 002 loss 2.0974 val_macro_f1 0.2988
2026-09-25 18:30:53,428 INFO   ep 003 loss 1.0621 val_macro_f1 0.4838 *
2026-09-25 18:30:53,807 INFO   ep 004 loss 0.8996 val_macro_f1 0.4163
2026-09-25 18:30:54,173 INFO   ep 005 loss 0.9119 val_macro_f1 0.5580 *
2026-09-25 18:30:54,565 INFO   ep 006 loss 0.7086 val_macro_f1 0.5089
2026-09-25 18:30:54,959 INFO   ep 007 loss 0.6563 val_macro_f1 0.5651 *
2026-09-25 18:30:55,354 INFO   ep 008 loss 0.8075 val_macro_f1 0.5016
2026-09-25 18:30:55,725 INFO   ep 009 loss 1.1201 val_macro_f1 0.6134 *
2026-09-25 18:30:56,107 INFO   ep 010 loss 1.7883 val_macro_f1 0.6332 *
2026-09-25 18:30:56,482 INFO   ep 011 loss 0.8484 val_macro_f1 0.6065
2026-09-25 18:30:56,858 INFO   ep 012 loss 0.7043 val_macro_f1 0.5688
2026-09-25 18:30:57,271 INFO   ep 013 loss 0.5732 val_macro_f1 0.6429 *
2026-09-25 18:30:57,696 INFO   ep 014 loss 0.7435 val_macro_f1 0.6459 *
2026-09-25 18:30:58,086 INFO   ep 015 loss 0.7426 val_macro_f1 0.6129
2026-09-25 18:30:58,473 INFO   ep 016 loss 0.4199 val_macro_f1 0.5514
2026-09-25 18:30:58,838 INFO   ep 017 loss 0.7901 val_macro_f1 0.6621 *
2026-09-25 18:30:59,215 INFO   ep 018 loss 0.5638 val_macro_f1 0.6411
2026-09-25 18:30:59,618 INFO   ep 019 loss 0.6562 val_macro_f1 0.6851 *
2026-09-25 18:30:59,986 INFO   ep 020 loss 0.5636 val_macro_f1 0.6809
2026-09-25 18:31:00,363 INFO   ep 021 loss 0.6220 val_macro_f1 0.7235 *
2026-09-25 18:31:00,730 INFO   ep 022 loss 0.4719 val_macro_f1 0.6811
2026-09-25 18:31:01,091 INFO   ep 023 loss 0.3744 val_macro_f1 0.7152
2026-09-25 18:31:01,460 INFO   ep 024 loss 0.4847 val_macro_f1 0.6769
2026-09-25 18:31:01,835 INFO   ep 025 loss 0.5213 val_macro_f1 0.7349 *
2026-09-25 18:31:02,217 INFO   ep 026 loss 0.3724 val_macro_f1 0.7444 *
2026-09-25 18:31:02,615 INFO   ep 027 loss 0.4902 val_macro_f1 0.7383
2026-09-25 18:31:02,992 INFO   ep 028 loss 0.1792 val_macro_f1 0.7132
2026-09-25 18:31:03,369 INFO   ep 029 loss 0.4439 val_macro_f1 0.7334
2026-09-25 18:31:03,743 INFO   ep 030 loss 0.3272 val_macro_f1 0.7371
2026-09-25 18:31:04,117 INFO   ep 031 loss 0.2546 val_macro_f1 0.7383
2026-09-25 18:31:04,498 INFO   ep 032 loss 0.2916 val_macro_f1 0.7462 *
2026-09-25 18:31:04,903 INFO   ep 033 loss 0.4387 val_macro_f1 0.7447
2026-09-25 18:31:05,310 INFO   ep 034 loss 0.3857 val_macro_f1 0.7373
2026-09-25 18:31:05,722 INFO   ep 035 loss 0.6249 val_macro_f1 0.7431
2026-09-25 18:31:06,106 INFO   ep 036 loss 0.2159 val_macro_f1 0.7027
2026-09-25 18:31:06,520 INFO   ep 037 loss 0.2485 val_macro_f1 0.7496 *
2026-09-25 18:31:06,889 INFO   ep 038 loss 0.2507 val_macro_f1 0.7292
2026-09-25 18:31:07,281 INFO   ep 039 loss 0.2494 val_macro_f1 0.7571 *
2026-09-25 18:31:07,649 INFO   ep 040 loss 0.1657 val_macro_f1 0.7450
2026-09-25 18:31:08,033 INFO   ep 041 loss 0.1704 val_macro_f1 0.7584 *
2026-09-25 18:31:08,478 INFO   ep 042 loss 0.1499 val_macro_f1 0.7542
2026-09-25 18:31:08,909 INFO   ep 043 loss 0.1727 val_macro_f1 0.7579
2026-09-25 18:31:09,363 INFO   ep 044 loss 0.1524 val_macro_f1 0.7545
2026-09-25 18:31:09,831 INFO   ep 045 loss 0.1708 val_macro_f1 0.7579
2026-09-25 18:31:10,197 INFO   ep 046 loss 0.1732 val_macro_f1 0.7596 *
2026-09-25 18:31:10,575 INFO   ep 047 loss 0.1709 val_macro_f1 0.7600 *
2026-09-25 18:31:10,941 INFO   ep 048 loss 0.1366 val_macro_f1 0.7583
2026-09-25 18:31:11,337 INFO   ep 049 loss 0.1230 val_macro_f1 0.7562
2026-09-25 18:31:11,717 INFO   ep 050 loss 0.1068 val_macro_f1 0.7449
2026-09-25 18:31:12,081 INFO   ep 051 loss 0.1856 val_macro_f1 0.7551
2026-09-25 18:31:12,444 INFO   ep 052 loss 0.0890 val_macro_f1 0.7475
2026-09-25 18:31:12,821 INFO   ep 053 loss 0.1249 val_macro_f1 0.7559
2026-09-25 18:31:13,200 INFO   ep 054 loss 0.1359 val_macro_f1 0.7553
2026-09-25 18:31:13,572 INFO   ep 055 loss 0.1021 val_macro_f1 0.7547
2026-09-25 18:31:13,940 INFO   ep 056 loss 0.0673 val_macro_f1 0.7432
2026-09-25 18:31:14,346 INFO   ep 057 loss 0.1073 val_macro_f1 0.7512
2026-09-25 18:31:14,715 INFO   ep 058 loss 0.0876 val_macro_f1 0.7391
2026-09-25 18:31:15,111 INFO   ep 059 loss 0.1361 val_macro_f1 0.7463
2026-09-25 18:31:15,512 INFO   ep 060 loss 0.0951 val_macro_f1 0.7573
2026-09-25 18:31:15,894 INFO   ep 061 loss 0.0648 val_macro_f1 0.7541
2026-09-25 18:31:16,265 INFO   ep 062 loss 0.1011 val_macro_f1 0.7460
2026-09-25 18:31:16,668 INFO   ep 063 loss 0.0597 val_macro_f1 0.7547
2026-09-25 18:31:17,052 INFO   ep 064 loss 0.0561 val_macro_f1 0.7569
2026-09-25 18:31:17,428 INFO   ep 065 loss 0.1130 val_macro_f1 0.7507
2026-09-25 18:31:17,805 INFO   ep 066 loss 0.1075 val_macro_f1 0.7542
2026-09-25 18:31:18,178 INFO   ep 067 loss 0.0911 val_macro_f1 0.7591
2026-09-25 18:31:18,549 INFO   ep 068 loss 0.0488 val_macro_f1 0.7580
2026-09-25 18:31:18,921 INFO   ep 069 loss 0.0960 val_macro_f1 0.7607 *
2026-09-25 18:31:19,301 INFO   ep 070 loss 0.0966 val_macro_f1 0.7538
2026-09-25 18:31:19,720 INFO   ep 071 loss 0.0635 val_macro_f1 0.7555
2026-09-25 18:31:20,088 INFO   ep 072 loss 0.0601 val_macro_f1 0.7512
2026-09-25 18:31:20,460 INFO   ep 073 loss 0.0619 val_macro_f1 0.7552
2026-09-25 18:31:20,821 INFO   ep 074 loss 0.0550 val_macro_f1 0.7560
2026-09-25 18:31:21,178 INFO   ep 075 loss 0.0538 val_macro_f1 0.7535
2026-09-25 18:31:21,570 INFO   ep 076 loss 0.0589 val_macro_f1 0.7557
2026-09-25 18:31:21,938 INFO   ep 077 loss 0.0424 val_macro_f1 0.7572
2026-09-25 18:31:22,328 INFO   ep 078 loss 0.0380 val_macro_f1 0.7547
2026-09-25 18:31:22,699 INFO   ep 079 loss 0.0565 val_macro_f1 0.7536
2026-09-25 18:31:23,094 INFO   ep 080 loss 0.0547 val_macro_f1 0.7528
2026-09-25 18:31:23,468 INFO   ep 081 loss 0.0483 val_macro_f1 0.7537
2026-09-25 18:31:23,860 INFO   ep 082 loss 0.0427 val_macro_f1 0.7531
2026-09-25 18:31:24,238 INFO   ep 083 loss 0.0372 val_macro_f1 0.7529
2026-09-25 18:31:24,601 INFO   ep 084 loss 0.0398 val_macro_f1 0.7514
2026-09-25 18:31:24,974 INFO   ep 085 loss 0.0574 val_macro_f1 0.7521
2026-09-25 18:31:25,331 INFO   ep 086 loss 0.0491 val_macro_f1 0.7556
2026-09-25 18:31:25,704 INFO   ep 087 loss 0.0585 val_macro_f1 0.7538
2026-09-25 18:31:26,066 INFO   ep 088 loss 0.0372 val_macro_f1 0.7513
2026-09-25 18:31:26,419 INFO   ep 089 loss 0.0476 val_macro_f1 0.7515
2026-09-25 18:31:26,786 INFO   ep 090 loss 0.0451 val_macro_f1 0.7541
2026-09-25 18:31:27,176 INFO   ep 091 loss 0.0565 val_macro_f1 0.7516
2026-09-25 18:31:27,556 INFO   ep 092 loss 0.0337 val_macro_f1 0.7503
2026-09-25 18:31:27,930 INFO   ep 093 loss 0.0341 val_macro_f1 0.7516
2026-09-25 18:31:28,301 INFO   ep 094 loss 0.0455 val_macro_f1 0.7484
2026-09-25 18:31:28,739 INFO   ep 095 loss 0.0477 val_macro_f1 0.7532
2026-09-25 18:31:29,122 INFO   ep 096 loss 0.0307 val_macro_f1 0.7506
2026-09-25 18:31:29,575 INFO   ep 097 loss 0.0318 val_macro_f1 0.7493
2026-09-25 18:31:29,943 INFO   ep 098 loss 0.0473 val_macro_f1 0.7494
2026-09-25 18:31:30,336 INFO   ep 099 loss 0.0497 val_macro_f1 0.7500
2026-09-25 18:31:30,733 INFO   ep 100 loss 0.0280 val_macro_f1 0.7504
2026-09-25 18:31:31,128 INFO   ep 101 loss 0.0546 val_macro_f1 0.7495
2026-09-25 18:31:31,517 INFO   ep 102 loss 0.0349 val_macro_f1 0.7520
2026-09-25 18:31:31,913 INFO   ep 103 loss 0.0471 val_macro_f1 0.7480
2026-09-25 18:31:32,304 INFO   ep 104 loss 0.0275 val_macro_f1 0.7512
2026-09-25 18:31:32,698 INFO   ep 105 loss 0.0306 val_macro_f1 0.7477
2026-09-25 18:31:33,091 INFO   ep 106 loss 0.0342 val_macro_f1 0.7477
2026-09-25 18:31:33,477 INFO   ep 107 loss 0.0453 val_macro_f1 0.7498
2026-09-25 18:31:33,852 INFO   ep 108 loss 0.0461 val_macro_f1 0.7464
2026-09-25 18:31:34,253 INFO   ep 109 loss 0.0322 val_macro_f1 0.7488
2026-09-25 18:31:34,628 INFO   ep 110 loss 0.0335 val_macro_f1 0.7484
2026-09-25 18:31:34,986 INFO   ep 111 loss 0.0380 val_macro_f1 0.7478
2026-09-25 18:31:35,359 INFO   ep 112 loss 0.0344 val_macro_f1 0.7470
2026-09-25 18:31:35,738 INFO   ep 113 loss 0.0264 val_macro_f1 0.7470
2026-09-25 18:31:36,147 INFO   ep 114 loss 0.0363 val_macro_f1 0.7466
2026-09-25 18:31:36,526 INFO   ep 115 loss 0.0379 val_macro_f1 0.7468
2026-09-25 18:31:36,892 INFO   ep 116 loss 0.0447 val_macro_f1 0.7471
2026-09-25 18:31:37,299 INFO   ep 117 loss 0.0261 val_macro_f1 0.7467
2026-09-25 18:31:37,681 INFO   ep 118 loss 0.0282 val_macro_f1 0.7468
2026-09-25 18:31:38,064 INFO   ep 119 loss 0.0518 val_macro_f1 0.7468
2026-09-25 18:31:39,483 INFO   ep 000 loss 1.5900 val_macro_f1 0.6527 *
2026-09-25 18:31:40,420 INFO   ep 001 loss 0.6927 val_macro_f1 0.6966 *
2026-09-25 18:31:41,358 INFO   ep 002 loss 1.2070 val_macro_f1 0.7195 *
2026-09-25 18:31:42,280 INFO   ep 003 loss 0.6621 val_macro_f1 0.7079
2026-09-25 18:31:43,251 INFO   ep 004 loss 0.6899 val_macro_f1 0.7119
2026-09-25 18:31:44,232 INFO   ep 005 loss 0.4599 val_macro_f1 0.7408 *
2026-09-25 18:31:45,187 INFO   ep 006 loss 0.5588 val_macro_f1 0.7111
2026-09-25 18:31:46,167 INFO   ep 007 loss 0.4601 val_macro_f1 0.7392
2026-09-25 18:31:47,125 INFO   ep 008 loss 0.6192 val_macro_f1 0.7247
2026-09-25 18:31:48,116 INFO   ep 009 loss 0.7691 val_macro_f1 0.7561 *
2026-09-25 18:31:49,083 INFO   ep 010 loss 0.7308 val_macro_f1 0.7385
2026-09-25 18:31:50,128 INFO   ep 011 loss 0.8402 val_macro_f1 0.7422
2026-09-25 18:31:51,069 INFO   ep 012 loss 0.1896 val_macro_f1 0.7543
2026-09-25 18:31:52,050 INFO   ep 013 loss 0.4183 val_macro_f1 0.7688 *
2026-09-25 18:31:53,026 INFO   ep 014 loss 0.5127 val_macro_f1 0.7711 *
2026-09-25 18:31:53,974 INFO   ep 015 loss 0.3634 val_macro_f1 0.7658
2026-09-25 18:31:54,922 INFO   ep 016 loss 0.2726 val_macro_f1 0.7379
2026-09-25 18:31:55,860 INFO   ep 017 loss 0.1804 val_macro_f1 0.7515
2026-09-25 18:31:56,833 INFO   ep 018 loss 0.7129 val_macro_f1 0.7714 *
2026-09-25 18:31:57,905 INFO   ep 019 loss 0.8012 val_macro_f1 0.7705
2026-09-25 18:31:58,923 INFO   ep 020 loss 0.2741 val_macro_f1 0.7731 *
2026-09-25 18:31:59,929 INFO   ep 021 loss 0.3649 val_macro_f1 0.7667
2026-09-25 18:32:00,898 INFO   ep 022 loss 0.2196 val_macro_f1 0.7754 *
2026-09-25 18:32:01,853 INFO   ep 023 loss 1.2090 val_macro_f1 0.7708
2026-09-25 18:32:02,804 INFO   ep 024 loss 0.3403 val_macro_f1 0.7549
2026-09-25 18:32:03,749 INFO   ep 025 loss 0.3068 val_macro_f1 0.7729
2026-09-25 18:32:04,722 INFO   ep 026 loss 0.4239 val_macro_f1 0.7597
2026-09-25 18:32:05,717 INFO   ep 027 loss 0.4407 val_macro_f1 0.7741
2026-09-25 18:32:06,674 INFO   ep 028 loss 0.3722 val_macro_f1 0.7725
2026-09-25 18:32:07,631 INFO   ep 029 loss 0.3517 val_macro_f1 0.7777 *
2026-09-25 18:32:08,589 INFO   ep 030 loss 0.2674 val_macro_f1 0.7815 *
2026-09-25 18:32:09,544 INFO   ep 031 loss 0.1707 val_macro_f1 0.7802
2026-09-25 18:32:10,479 INFO   ep 032 loss 0.5261 val_macro_f1 0.7682
2026-09-25 18:32:11,404 INFO   ep 033 loss 0.3950 val_macro_f1 0.7716
2026-09-25 18:32:12,444 INFO   ep 034 loss 0.4646 val_macro_f1 0.7874 *
2026-09-25 18:32:13,405 INFO   ep 035 loss 0.2350 val_macro_f1 0.7900 *
2026-09-25 18:32:14,344 INFO   ep 036 loss 0.1592 val_macro_f1 0.7884
2026-09-25 18:32:15,348 INFO   ep 037 loss 0.3766 val_macro_f1 0.7843
2026-09-25 18:32:16,314 INFO   ep 038 loss 0.1599 val_macro_f1 0.7833
2026-09-25 18:32:17,254 INFO   ep 039 loss 0.2423 val_macro_f1 0.7807
2026-09-25 18:32:18,234 INFO   ep 040 loss 0.1293 val_macro_f1 0.7805
2026-09-25 18:32:19,202 INFO   ep 041 loss 0.2192 val_macro_f1 0.7869
2026-09-25 18:32:20,193 INFO   ep 042 loss 0.3629 val_macro_f1 0.7852
2026-09-25 18:32:21,177 INFO   ep 043 loss 0.1323 val_macro_f1 0.7923 *
2026-09-25 18:32:22,127 INFO   ep 044 loss 0.1262 val_macro_f1 0.7731
2026-09-25 18:32:23,109 INFO   ep 045 loss 0.2202 val_macro_f1 0.7787
2026-09-25 18:32:24,074 INFO   ep 046 loss 0.2393 val_macro_f1 0.7758
2026-09-25 18:32:25,011 INFO   ep 047 loss 0.1979 val_macro_f1 0.7876
2026-09-25 18:32:25,956 INFO   ep 048 loss 0.1010 val_macro_f1 0.7856
2026-09-25 18:32:26,907 INFO   ep 049 loss 0.1698 val_macro_f1 0.7853
2026-09-25 18:32:27,854 INFO   ep 050 loss 0.0928 val_macro_f1 0.7858
2026-09-25 18:32:28,799 INFO   ep 051 loss 0.1401 val_macro_f1 0.7845
2026-09-25 18:32:29,817 INFO   ep 052 loss 0.0723 val_macro_f1 0.7903
2026-09-25 18:32:30,787 INFO   ep 053 loss 0.1376 val_macro_f1 0.7833
2026-09-25 18:32:31,742 INFO   ep 054 loss 0.1211 val_macro_f1 0.7873
2026-09-25 18:32:32,706 INFO   ep 055 loss 0.1057 val_macro_f1 0.7872
2026-09-25 18:32:33,664 INFO   ep 056 loss 0.0758 val_macro_f1 0.7892
2026-09-25 18:32:34,629 INFO   ep 057 loss 0.1298 val_macro_f1 0.7905
2026-09-25 18:32:35,613 INFO   ep 058 loss 0.0497 val_macro_f1 0.7821
2026-09-25 18:32:36,599 INFO   ep 059 loss 0.1495 val_macro_f1 0.7829
2026-09-25 18:32:37,611 INFO   ep 060 loss 0.2817 val_macro_f1 0.7961 *
2026-09-25 18:32:38,595 INFO   ep 061 loss 0.0794 val_macro_f1 0.7859
2026-09-25 18:32:39,595 INFO   ep 062 loss 0.1056 val_macro_f1 0.7847
2026-09-25 18:32:40,634 INFO   ep 063 loss 0.1336 val_macro_f1 0.7923
2026-09-25 18:32:41,669 INFO   ep 064 loss 0.0712 val_macro_f1 0.7912
2026-09-25 18:32:42,699 INFO   ep 065 loss 0.1118 val_macro_f1 0.7950
2026-09-25 18:32:43,663 INFO   ep 066 loss 0.0752 val_macro_f1 0.7919
2026-09-25 18:32:44,634 INFO   ep 067 loss 0.0927 val_macro_f1 0.7913
2026-09-25 18:32:45,635 INFO   ep 068 loss 0.0259 val_macro_f1 0.7965 *
2026-09-25 18:32:46,579 INFO   ep 069 loss 0.0478 val_macro_f1 0.7933
2026-09-25 18:32:47,528 INFO   ep 070 loss 0.1115 val_macro_f1 0.7872
2026-09-25 18:32:48,458 INFO   ep 071 loss 0.0635 val_macro_f1 0.7897
2026-09-25 18:32:49,468 INFO   ep 072 loss 0.0480 val_macro_f1 0.7877
2026-09-25 18:32:50,411 INFO   ep 073 loss 0.1093 val_macro_f1 0.7956
2026-09-25 18:32:51,362 INFO   ep 074 loss 0.0225 val_macro_f1 0.7900
2026-09-25 18:32:52,315 INFO   ep 075 loss 0.0323 val_macro_f1 0.7895
2026-09-25 18:32:53,272 INFO   ep 076 loss 0.0401 val_macro_f1 0.7929
2026-09-25 18:32:54,269 INFO   ep 077 loss 0.0215 val_macro_f1 0.7943
2026-09-25 18:32:55,229 INFO   ep 078 loss 0.0301 val_macro_f1 0.7950
2026-09-25 18:32:56,217 INFO   ep 079 loss 0.0340 val_macro_f1 0.7941
2026-09-25 18:32:57,206 INFO   ep 080 loss 0.0797 val_macro_f1 0.7953
2026-09-25 18:32:58,199 INFO   ep 081 loss 0.0595 val_macro_f1 0.7884
2026-09-25 18:32:59,187 INFO   ep 082 loss 0.0515 val_macro_f1 0.7944
2026-09-25 18:33:00,171 INFO   ep 083 loss 0.0256 val_macro_f1 0.7863
2026-09-25 18:33:01,116 INFO   ep 084 loss 0.0437 val_macro_f1 0.7886
2026-09-25 18:33:02,096 INFO   ep 085 loss 0.0251 val_macro_f1 0.7916
2026-09-25 18:33:03,087 INFO   ep 086 loss 0.0292 val_macro_f1 0.7890
2026-09-25 18:33:04,060 INFO   ep 087 loss 0.1009 val_macro_f1 0.7885
2026-09-25 18:33:05,057 INFO   ep 088 loss 0.0223 val_macro_f1 0.7908
2026-09-25 18:33:06,033 INFO   ep 089 loss 0.0090 val_macro_f1 0.7931
2026-09-25 18:33:06,999 INFO   ep 090 loss 0.0239 val_macro_f1 0.7932
2026-09-25 18:33:07,974 INFO   ep 091 loss 0.0644 val_macro_f1 0.7938
2026-09-25 18:33:08,936 INFO   ep 092 loss 0.0899 val_macro_f1 0.7916
2026-09-25 18:33:09,954 INFO   ep 093 loss 0.0428 val_macro_f1 0.7934
2026-09-25 18:33:10,938 INFO   ep 094 loss 0.0834 val_macro_f1 0.7926
2026-09-25 18:33:11,944 INFO   ep 095 loss 0.0204 val_macro_f1 0.7867
2026-09-25 18:33:12,941 INFO   ep 096 loss 0.0053 val_macro_f1 0.7932
2026-09-25 18:33:13,923 INFO   ep 097 loss 0.0877 val_macro_f1 0.7942
2026-09-25 18:33:14,915 INFO   ep 098 loss 0.0733 val_macro_f1 0.7932
2026-09-25 18:33:15,902 INFO   ep 099 loss 0.0511 val_macro_f1 0.7913
2026-09-25 18:33:16,892 INFO   ep 100 loss 0.0210 val_macro_f1 0.7902
2026-09-25 18:33:17,883 INFO   ep 101 loss 0.0447 val_macro_f1 0.7880
2026-09-25 18:33:18,870 INFO   ep 102 loss 0.0304 val_macro_f1 0.7894
2026-09-25 18:33:19,894 INFO   ep 103 loss 0.0272 val_macro_f1 0.7899
2026-09-25 18:33:20,886 INFO   ep 104 loss 0.0030 val_macro_f1 0.7922
2026-09-25 18:33:21,899 INFO   ep 105 loss 0.0280 val_macro_f1 0.7921
2026-09-25 18:33:22,907 INFO   ep 106 loss 0.0209 val_macro_f1 0.7923
2026-09-25 18:33:23,882 INFO   ep 107 loss 0.0275 val_macro_f1 0.7919
2026-09-25 18:33:24,842 INFO   ep 108 loss 0.0491 val_macro_f1 0.7929
2026-09-25 18:33:25,788 INFO   ep 109 loss 0.0082 val_macro_f1 0.7930
2026-09-25 18:33:26,729 INFO   ep 110 loss 0.0293 val_macro_f1 0.7930
2026-09-25 18:33:27,682 INFO   ep 111 loss 0.0254 val_macro_f1 0.7912
2026-09-25 18:33:28,644 INFO   ep 112 loss 0.0794 val_macro_f1 0.7908
2026-09-25 18:33:29,666 INFO   ep 113 loss 0.0356 val_macro_f1 0.7917
2026-09-25 18:33:30,645 INFO   ep 114 loss 0.0278 val_macro_f1 0.7917
2026-09-25 18:33:31,613 INFO   ep 115 loss 0.0080 val_macro_f1 0.7917
2026-09-25 18:33:32,597 INFO   ep 116 loss 0.0322 val_macro_f1 0.7916
2026-09-25 18:33:33,586 INFO   ep 117 loss 0.0305 val_macro_f1 0.7918
2026-09-25 18:33:34,562 INFO   ep 118 loss 0.0100 val_macro_f1 0.7917
2026-09-25 18:33:35,533 INFO   ep 119 loss 0.0441 val_macro_f1 0.7917
2026-09-25 18:33:35,677 INFO seed0: Spearman(M, A_lgc)=0.750  Spearman(M, attn_lat)=-0.217
2026-09-25 18:33:36,098 INFO   ep 000 loss 2.5964 val_macro_f1 0.4113 *
2026-09-25 18:33:36,500 INFO   ep 001 loss 1.4463 val_macro_f1 0.4382 *
2026-09-25 18:33:36,905 INFO   ep 002 loss 2.0134 val_macro_f1 0.3516
2026-09-25 18:33:37,302 INFO   ep 003 loss 1.0111 val_macro_f1 0.5595 *
2026-09-25 18:33:37,712 INFO   ep 004 loss 0.7817 val_macro_f1 0.5604 *
2026-09-25 18:33:38,131 INFO   ep 005 loss 0.7321 val_macro_f1 0.5781 *
2026-09-25 18:33:38,527 INFO   ep 006 loss 0.8086 val_macro_f1 0.5367
2026-09-25 18:33:38,949 INFO   ep 007 loss 0.7451 val_macro_f1 0.4361
2026-09-25 18:33:39,369 INFO   ep 008 loss 0.6855 val_macro_f1 0.5659
2026-09-25 18:33:39,803 INFO   ep 009 loss 0.8289 val_macro_f1 0.5309
2026-09-25 18:33:40,215 INFO   ep 010 loss 1.2231 val_macro_f1 0.5575
2026-09-25 18:33:40,617 INFO   ep 011 loss 1.0620 val_macro_f1 0.6296 *
2026-09-25 18:33:41,037 INFO   ep 012 loss 0.6901 val_macro_f1 0.6033
2026-09-25 18:33:41,436 INFO   ep 013 loss 0.5615 val_macro_f1 0.6507 *
2026-09-25 18:33:41,848 INFO   ep 014 loss 0.6479 val_macro_f1 0.6079
2026-09-25 18:33:42,260 INFO   ep 015 loss 0.8216 val_macro_f1 0.6646 *
2026-09-25 18:33:42,671 INFO   ep 016 loss 0.4230 val_macro_f1 0.4459
2026-09-25 18:33:43,091 INFO   ep 017 loss 0.7788 val_macro_f1 0.6737 *
2026-09-25 18:33:43,500 INFO   ep 018 loss 0.6548 val_macro_f1 0.6659
2026-09-25 18:33:43,910 INFO   ep 019 loss 0.6682 val_macro_f1 0.6549
2026-09-25 18:33:44,319 INFO   ep 020 loss 0.6879 val_macro_f1 0.6902 *
2026-09-25 18:33:44,768 INFO   ep 021 loss 0.5522 val_macro_f1 0.7090 *
2026-09-25 18:33:45,188 INFO   ep 022 loss 0.4746 val_macro_f1 0.7210 *
2026-09-25 18:33:45,590 INFO   ep 023 loss 0.3805 val_macro_f1 0.6703
2026-09-25 18:33:45,994 INFO   ep 024 loss 0.5189 val_macro_f1 0.6981
2026-09-25 18:33:46,402 INFO   ep 025 loss 0.4737 val_macro_f1 0.7204
2026-09-25 18:33:46,806 INFO   ep 026 loss 0.5984 val_macro_f1 0.7234 *
2026-09-25 18:33:47,208 INFO   ep 027 loss 0.6774 val_macro_f1 0.7112
2026-09-25 18:33:47,640 INFO   ep 028 loss 0.2459 val_macro_f1 0.7361 *
2026-09-25 18:33:48,056 INFO   ep 029 loss 0.4074 val_macro_f1 0.7324
2026-09-25 18:33:48,460 INFO   ep 030 loss 0.3927 val_macro_f1 0.7368 *
2026-09-25 18:33:48,900 INFO   ep 031 loss 0.3092 val_macro_f1 0.7374 *
2026-09-25 18:33:49,343 INFO   ep 032 loss 0.2695 val_macro_f1 0.7368
2026-09-25 18:33:49,799 INFO   ep 033 loss 0.3044 val_macro_f1 0.7551 *
2026-09-25 18:33:50,211 INFO   ep 034 loss 0.4112 val_macro_f1 0.7347
2026-09-25 18:33:50,628 INFO   ep 035 loss 0.3184 val_macro_f1 0.7473
2026-09-25 18:33:51,044 INFO   ep 036 loss 0.4622 val_macro_f1 0.7484
2026-09-25 18:33:51,472 INFO   ep 037 loss 0.2121 val_macro_f1 0.7584 *
2026-09-25 18:33:51,876 INFO   ep 038 loss 0.2531 val_macro_f1 0.7370
2026-09-25 18:33:52,273 INFO   ep 039 loss 0.2101 val_macro_f1 0.7591 *
2026-09-25 18:33:52,664 INFO   ep 040 loss 0.1899 val_macro_f1 0.7644 *
2026-09-25 18:33:53,091 INFO   ep 041 loss 0.2260 val_macro_f1 0.7709 *

In [4]:
# R2#8: head- and layer-resolved attention, checking whether averaging across
# heads/layers/samples (as in the headline rho figure) hides finer structure.
# Run on F_post, where the H5 label-conditioning exception was observed.
#
# Follow-up fix: the single SEEDS[0]-only run below did not replicate across kernel
# restarts (GPU/cuDNN non-determinism), so a specific head/layer's correlation is
# not a defensible finding on its own. Loop over all 3 seeds and only report a
# head/layer combo as notable if it's consistently non-trivial across seeds --
# otherwise the honest read is "no stable head/layer signal, average is representative."
d_post = scvd.make_data(pre, post, lab, fam, 'post', *splits['S1'])
M_post = scvd.cooccurrence(d_post['y_tr'])

head_rows = []
avg_rhos = []
for seed in SEEDS:
    scvd.set_seed(seed)
    lat_post = scvd.LAT(d_post['fams'], dm=128, layers=3)
    _, _h = scvd.train_torch(lat_post, d_post, cfg, log)

    A_full = scvd.extract_label_attention_full(lat_post, d_post)   # (layers, heads, 8, 8)
    n_layers, n_heads = A_full.shape[:2]
    for li in range(n_layers):
        for hi in range(n_heads):
            head_rows.append({'seed': seed, 'layer': li, 'head': hi,
                               'rho': spearmanr(M_post[off], A_full[li, hi][off]).statistic})

    avg_attn_post = scvd.extract_label_attention(lat_post, d_post)   # head/layer-averaged, for comparison
    rho_avg_post = spearmanr(M_post[off], avg_attn_post[off]).statistic
    avg_rhos.append(rho_avg_post)
    log.info('seed%d F_post attention: averaged rho=%.3f', seed, rho_avg_post)

head_df = pd.DataFrame(head_rows)
head_df.to_csv(f'{root}/results/stage5_attention_by_head_post.csv', index=False)

# per (layer, head): is the sign/magnitude consistent across all 3 seeds, or is it noise?
stab = (head_df.groupby(['layer', 'head'])['rho']
        .agg(['mean', 'min', 'max'])
        .assign(consistent_sign=lambda x: np.sign(x['min']) == np.sign(x['max']))
        .reset_index())
stab.to_csv(f'{root}/results/stage5_attention_by_head_post_stability.csv', index=False)
log.info('F_post attention: averaged rho mean=%.3f range=[%.3f,%.3f]',
          np.mean(avg_rhos), min(avg_rhos), max(avg_rhos))
log.info('head/layer cells with a consistent sign across all 3 seeds: %d of %d',
          int(stab['consistent_sign'].sum()), len(stab))
stab.sort_values('mean', ascending=False)

2026-09-25 18:39:17,591 INFO   ep 000 loss 1.4577 val_macro_f1 0.5525 *
2026-09-25 18:39:18,499 INFO   ep 001 loss 1.1200 val_macro_f1 0.6079 *
2026-09-25 18:39:19,446 INFO   ep 002 loss 1.4976 val_macro_f1 0.6473 *
2026-09-25 18:39:20,391 INFO   ep 003 loss 0.7964 val_macro_f1 0.6334
2026-09-25 18:39:21,306 INFO   ep 004 loss 0.7058 val_macro_f1 0.5848
2026-09-25 18:39:22,251 INFO   ep 005 loss 0.6358 val_macro_f1 0.6501 *
2026-09-25 18:39:23,143 INFO   ep 006 loss 0.7669 val_macro_f1 0.6475
2026-09-25 18:39:24,099 INFO   ep 007 loss 0.4399 val_macro_f1 0.6593 *
2026-09-25 18:39:25,011 INFO   ep 008 loss 0.8407 val_macro_f1 0.6444
2026-09-25 18:39:25,949 INFO   ep 009 loss 0.6542 val_macro_f1 0.6643 *
2026-09-25 18:39:26,879 INFO   ep 010 loss 0.7410 val_macro_f1 0.6693 *
2026-09-25 18:39:27,815 INFO   ep 011 loss 0.8271 val_macro_f1 0.6550
2026-09-25 18:39:28,794 INFO   ep 012 loss 0.7882 val_macro_f1 0.6839 *
2026-09-25 18:39:29,784 INFO   ep 013 loss 0.6186 val_macro_f1 0.6756
2026-09-25 18:39:30,734 INFO   ep 014 loss 0.7731 val_macro_f1 0.6619
2026-09-25 18:39:31,685 INFO   ep 015 loss 0.6437 val_macro_f1 0.6742
2026-09-25 18:39:32,581 INFO   ep 016 loss 0.4209 val_macro_f1 0.6755
2026-09-25 18:39:33,491 INFO   ep 017 loss 0.6195 val_macro_f1 0.6761
2026-09-25 18:39:34,452 INFO   ep 018 loss 1.3937 val_macro_f1 0.6898 *
2026-09-25 18:39:35,410 INFO   ep 019 loss 0.7145 val_macro_f1 0.6764
2026-09-25 18:39:36,352 INFO   ep 020 loss 0.5293 val_macro_f1 0.6820
2026-09-25 18:39:37,338 INFO   ep 021 loss 0.3181 val_macro_f1 0.6907 *
2026-09-25 18:39:38,286 INFO   ep 022 loss 0.4669 val_macro_f1 0.6880
2026-09-25 18:39:39,239 INFO   ep 023 loss 1.6728 val_macro_f1 0.6658
2026-09-25 18:39:40,235 INFO   ep 024 loss 0.4315 val_macro_f1 0.6998 *
2026-09-25 18:39:41,162 INFO   ep 025 loss 0.5630 val_macro_f1 0.6840
2026-09-25 18:39:42,107 INFO   ep 026 loss 0.6391 val_macro_f1 0.6959
2026-09-25 18:39:43,053 INFO   ep 027 loss 1.1649 val_macro_f1 0.6934
2026-09-25 18:39:44,015 INFO   ep 028 loss 0.3434 val_macro_f1 0.6949
2026-09-25 18:39:45,021 INFO   ep 029 loss 0.4049 val_macro_f1 0.6861
2026-09-25 18:39:46,068 INFO   ep 030 loss 0.3864 val_macro_f1 0.6981
2026-09-25 18:39:47,068 INFO   ep 031 loss 0.2536 val_macro_f1 0.6987
2026-09-25 18:39:48,054 INFO   ep 032 loss 0.5216 val_macro_f1 0.6894
2026-09-25 18:39:49,019 INFO   ep 033 loss 0.4686 val_macro_f1 0.6918
2026-09-25 18:39:50,065 INFO   ep 034 loss 0.7149 val_macro_f1 0.7058 *
2026-09-25 18:39:51,043 INFO   ep 035 loss 0.4190 val_macro_f1 0.7049
2026-09-25 18:39:52,012 INFO   ep 036 loss 0.4156 val_macro_f1 0.6990
2026-09-25 18:39:52,943 INFO   ep 037 loss 0.2678 val_macro_f1 0.6942
2026-09-25 18:39:53,899 INFO   ep 038 loss 0.4344 val_macro_f1 0.7062 *
2026-09-25 18:39:54,839 INFO   ep 039 loss 0.4288 val_macro_f1 0.7058
2026-09-25 18:39:55,763 INFO   ep 040 loss 0.4287 val_macro_f1 0.7026
2026-09-25 18:39:56,687 INFO   ep 041 loss 0.6868 val_macro_f1 0.7007
2026-09-25 18:39:57,616 INFO   ep 042 loss 0.4569 val_macro_f1 0.7024
2026-09-25 18:39:58,616 INFO   ep 043 loss 0.6058 val_macro_f1 0.7036
2026-09-25 18:39:59,663 INFO   ep 044 loss 0.3975 val_macro_f1 0.7038
2026-09-25 18:40:00,661 INFO   ep 045 loss 0.2222 val_macro_f1 0.6952
2026-09-25 18:40:01,641 INFO   ep 046 loss 0.5204 val_macro_f1 0.7063 *
2026-09-25 18:40:02,628 INFO   ep 047 loss 0.3314 val_macro_f1 0.7131 *
2026-09-25 18:40:03,583 INFO   ep 048 loss 0.3489 val_macro_f1 0.7094
2026-09-25 18:40:04,517 INFO   ep 049 loss 0.3981 val_macro_f1 0.7046
2026-09-25 18:40:05,443 INFO   ep 050 loss 0.4786 val_macro_f1 0.6988
2026-09-25 18:40:06,364 INFO   ep 051 loss 0.2253 val_macro_f1 0.7012
2026-09-25 18:40:07,280 INFO   ep 052 loss 0.1351 val_macro_f1 0.6939
2026-09-25 18:40:08,223 INFO   ep 053 loss 0.4583 val_macro_f1 0.7031
2026-09-25 18:40:09,156 INFO   ep 054 loss 0.3648 val_macro_f1 0.7050
2026-09-25 18:40:10,130 INFO   ep 055 loss 0.2119 val_macro_f1 0.7104
2026-09-25 18:40:11,062 INFO   ep 056 loss 0.1994 val_macro_f1 0.6971
2026-09-25 18:40:11,968 INFO   ep 057 loss 0.2639 val_macro_f1 0.7036
2026-09-25 18:40:12,924 INFO   ep 058 loss 0.1007 val_macro_f1 0.7137 *
2026-09-25 18:40:13,847 INFO   ep 059 loss 0.2895 val_macro_f1 0.7132
2026-09-25 18:40:14,766 INFO   ep 060 loss 0.2447 val_macro_f1 0.7103
2026-09-25 18:40:15,688 INFO   ep 061 loss 0.1836 val_macro_f1 0.7109
2026-09-25 18:40:16,693 INFO   ep 062 loss 0.3803 val_macro_f1 0.7080
2026-09-25 18:40:17,647 INFO   ep 063 loss 0.1956 val_macro_f1 0.7137
2026-09-25 18:40:18,568 INFO   ep 064 loss 0.3925 val_macro_f1 0.7109
2026-09-25 18:40:19,540 INFO   ep 065 loss 0.1944 val_macro_f1 0.7088
2026-09-25 18:40:20,454 INFO   ep 066 loss 0.2633 val_macro_f1 0.7024
2026-09-25 18:40:21,397 INFO   ep 067 loss 0.2535 val_macro_f1 0.7093
2026-09-25 18:40:22,355 INFO   ep 068 loss 0.1057 val_macro_f1 0.7140 *
2026-09-25 18:40:23,274 INFO   ep 069 loss 0.2552 val_macro_f1 0.7073
2026-09-25 18:40:24,186 INFO   ep 070 loss 0.2048 val_macro_f1 0.7121
2026-09-25 18:40:25,077 INFO   ep 071 loss 0.0972 val_macro_f1 0.7090
2026-09-25 18:40:25,998 INFO   ep 072 loss 0.2478 val_macro_f1 0.7070
2026-09-25 18:40:26,924 INFO   ep 073 loss 0.1817 val_macro_f1 0.7138
2026-09-25 18:40:27,848 INFO   ep 074 loss 0.2428 val_macro_f1 0.7165 *
2026-09-25 18:40:28,784 INFO   ep 075 loss 0.0936 val_macro_f1 0.7121
2026-09-25 18:40:29,743 INFO   ep 076 loss 0.1183 val_macro_f1 0.7091
2026-09-25 18:40:30,666 INFO   ep 077 loss 0.2109 val_macro_f1 0.7062
2026-09-25 18:40:31,578 INFO   ep 078 loss 0.1671 val_macro_f1 0.7077
2026-09-25 18:40:32,563 INFO   ep 079 loss 0.5716 val_macro_f1 0.7129
2026-09-25 18:40:33,506 INFO   ep 080 loss 0.1596 val_macro_f1 0.7095
2026-09-25 18:40:34,453 INFO   ep 081 loss 0.2346 val_macro_f1 0.7087
2026-09-25 18:40:35,385 INFO   ep 082 loss 0.1497 val_macro_f1 0.7103
2026-09-25 18:40:36,340 INFO   ep 083 loss 0.1860 val_macro_f1 0.7021
2026-09-25 18:40:37,262 INFO   ep 084 loss 0.1159 val_macro_f1 0.7101
2026-09-25 18:40:38,222 INFO   ep 085 loss 0.1536 val_macro_f1 0.7044
2026-09-25 18:40:39,144 INFO   ep 086 loss 0.1189 val_macro_f1 0.7069
2026-09-25 18:40:40,117 INFO   ep 087 loss 0.1143 val_macro_f1 0.7094
2026-09-25 18:40:41,042 INFO   ep 088 loss 0.0993 val_macro_f1 0.7019
2026-09-25 18:40:41,958 INFO   ep 089 loss 0.1291 val_macro_f1 0.7061
2026-09-25 18:40:42,881 INFO   ep 090 loss 0.0964 val_macro_f1 0.7068
2026-09-25 18:40:43,810 INFO   ep 091 loss 0.1985 val_macro_f1 0.7034
2026-09-25 18:40:44,726 INFO   ep 092 loss 0.1503 val_macro_f1 0.7077
2026-09-25 18:40:45,649 INFO   ep 093 loss 0.1611 val_macro_f1 0.7087
2026-09-25 18:40:46,575 INFO   ep 094 loss 0.1079 val_macro_f1 0.7056
2026-09-25 18:40:47,528 INFO   ep 095 loss 0.0655 val_macro_f1 0.7067
2026-09-25 18:40:48,467 INFO   ep 096 loss 0.0834 val_macro_f1 0.7065
2026-09-25 18:40:49,440 INFO   ep 097 loss 0.1275 val_macro_f1 0.7099
2026-09-25 18:40:50,395 INFO   ep 098 loss 0.1348 val_macro_f1 0.7032
2026-09-25 18:40:51,354 INFO   ep 099 loss 0.2211 val_macro_f1 0.7101
2026-09-25 18:40:52,307 INFO   ep 100 loss 0.0713 val_macro_f1 0.7077
2026-09-25 18:40:53,246 INFO   ep 101 loss 0.1025 val_macro_f1 0.7108
2026-09-25 18:40:54,159 INFO   ep 102 loss 0.0405 val_macro_f1 0.7104
2026-09-25 18:40:55,069 INFO   ep 103 loss 0.1173 val_macro_f1 0.7110
2026-09-25 18:40:56,016 INFO   ep 104 loss 0.0989 val_macro_f1 0.7079
2026-09-25 18:40:56,969 INFO   ep 105 loss 0.1229 val_macro_f1 0.7083
2026-09-25 18:40:57,918 INFO   ep 106 loss 0.0772 val_macro_f1 0.7114
2026-09-25 18:40:58,815 INFO   ep 107 loss 0.0941 val_macro_f1 0.7093
2026-09-25 18:40:59,775 INFO   ep 108 loss 0.1605 val_macro_f1 0.7081
2026-09-25 18:41:00,698 INFO   ep 109 loss 0.1007 val_macro_f1 0.7086
2026-09-25 18:41:01,642 INFO   ep 110 loss 0.0616 val_macro_f1 0.7087
2026-09-25 18:41:02,596 INFO   ep 111 loss 0.1392 val_macro_f1 0.7092
2026-09-25 18:41:03,580 INFO   ep 112 loss 0.1918 val_macro_f1 0.7083
2026-09-25 18:41:04,545 INFO   ep 113 loss 0.1154 val_macro_f1 0.7089
2026-09-25 18:41:05,470 INFO   ep 114 loss 0.0511 val_macro_f1 0.7095
2026-09-25 18:41:06,424 INFO   ep 115 loss 0.0904 val_macro_f1 0.7086
2026-09-25 18:41:07,385 INFO   ep 116 loss 0.1336 val_macro_f1 0.7086
2026-09-25 18:41:08,350 INFO   ep 117 loss 0.1175 val_macro_f1 0.7085
2026-09-25 18:41:09,326 INFO   ep 118 loss 0.0762 val_macro_f1 0.7086
2026-09-25 18:41:10,336 INFO   ep 119 loss 0.1648 val_macro_f1 0.7086
2026-09-25 18:41:10,411 INFO seed0 F_post attention: averaged rho=-0.226
2026-09-25 18:41:11,412 INFO   ep 000 loss 1.0588 val_macro_f1 0.5068 *
2026-09-25 18:41:12,400 INFO   ep 001 loss 1.1208 val_macro_f1 0.6233 *
2026-09-25 18:41:13,356 INFO   ep 002 loss 1.5234 val_macro_f1 0.6445 *
2026-09-25 18:41:14,308 INFO   ep 003 loss 0.8172 val_macro_f1 0.6603 *
2026-09-25 18:41:15,235 INFO   ep 004 loss 0.7624 val_macro_f1 0.6114
2026-09-25 18:41:16,237 INFO   ep 005 loss 0.5942 val_macro_f1 0.6515
2026-09-25 18:41:17,197 INFO   ep 006 loss 0.7375 val_macro_f1 0.6260
2026-09-25 18:41:18,122 INFO   ep 007 loss 0.5374 val_macro_f1 0.6488
2026-09-25 18:41:19,081 INFO   ep 008 loss 1.2280 val_macro_f1 0.6794 *
2026-09-25 18:41:20,044 INFO   ep 009 loss 0.6439 val_macro_f1 0.6735
2026-09-25 18:41:20,968 INFO   ep 010 loss 1.5060 val_macro_f1 0.6787
2026-09-25 18:41:21,883 INFO   ep 011 loss 0.7054 val_macro_f1 0.6418
2026-09-25 18:41:22,803 INFO   ep 012 loss 0.7551 val_macro_f1 0.6761
2026-09-25 18:41:23,781 INFO   ep 013 loss 0.5854 val_macro_f1 0.6830 *
2026-09-25 18:41:24,757 INFO   ep 014 loss 0.5314 val_macro_f1 0.6954 *
2026-09-25 18:41:25,743 INFO   ep 015 loss 0.6180 val_macro_f1 0.6983 *
2026-09-25 18:41:26,675 INFO   ep 016 loss 0.5837 val_macro_f1 0.6668
2026-09-25 18:41:27,628 INFO   ep 017 loss 0.5201 val_macro_f1 0.6972
2026-09-25 18:41:28,578 INFO   ep 018 loss 1.4505 val_macro_f1 0.6896
2026-09-25 18:41:29,577 INFO   ep 019 loss 1.0507 val_macro_f1 0.6813
2026-09-25 18:41:30,518 INFO   ep 020 loss 0.5406 val_macro_f1 0.6864
2026-09-25 18:41:31,459 INFO   ep 021 loss 0.3380 val_macro_f1 0.6935
2026-09-25 18:41:32,406 INFO   ep 022 loss 0.5606 val_macro_f1 0.6933
2026-09-25 18:41:33,336 INFO   ep 023 loss 0.5103 val_macro_f1 0.6735
2026-09-25 18:41:34,247 INFO   ep 024 loss 0.3754 val_macro_f1 0.7014 *
2026-09-25 18:41:35,151 INFO   ep 025 loss 0.3694 val_macro_f1 0.6905
2026-09-25 18:41:36,081 INFO   ep 026 loss 1.8666 val_macro_f1 0.6885
2026-09-25 18:41:37,028 INFO   ep 027 loss 1.5393 val_macro_f1 0.6843
2026-09-25 18:41:38,012 INFO   ep 028 loss 0.3117 val_macro_f1 0.6799
2026-09-25 18:41:39,011 INFO   ep 029 loss 1.2183 val_macro_f1 0.6927
2026-09-25 18:41:40,037 INFO   ep 030 loss 0.5238 val_macro_f1 0.6769
2026-09-25 18:41:41,000 INFO   ep 031 loss 0.3188 val_macro_f1 0.6992
2026-09-25 18:41:41,978 INFO   ep 032 loss 0.2973 val_macro_f1 0.7018 *
2026-09-25 18:41:42,897 INFO   ep 033 loss 0.3577 val_macro_f1 0.6977
2026-09-25 18:41:43,923 INFO   ep 034 loss 0.6593 val_macro_f1 0.6976
2026-09-25 18:41:44,834 INFO   ep 035 loss 0.3779 val_macro_f1 0.7002
2026-09-25 18:41:45,815 INFO   ep 036 loss 0.4020 val_macro_f1 0.7041 *
2026-09-25 18:41:46,785 INFO   ep 037 loss 0.2558 val_macro_f1 0.6938
2026-09-25 18:41:47,771 INFO   ep 038 loss 0.5580 val_macro_f1 0.7089 *
2026-09-25 18:41:48,726 INFO   ep 039 loss 1.5595 val_macro_f1 0.7072
2026-09-25 18:41:49,737 INFO   ep 040 loss 0.3667 val_macro_f1 0.6994
2026-09-25 18:41:50,687 INFO   ep 041 loss 0.4947 val_macro_f1 0.7063
2026-09-25 18:41:51,608 INFO   ep 042 loss 0.6392 val_macro_f1 0.7020
2026-09-25 18:41:52,599 INFO   ep 043 loss 0.2978 val_macro_f1 0.6988
2026-09-25 18:41:53,526 INFO   ep 044 loss 0.4241 val_macro_f1 0.6981
2026-09-25 18:41:54,458 INFO   ep 045 loss 0.3872 val_macro_f1 0.6939
2026-09-25 18:41:55,381 INFO   ep 046 loss 0.2545 val_macro_f1 0.6825
2026-09-25 18:41:56,311 INFO   ep 047 loss 0.2983 val_macro_f1 0.7001
2026-09-25 18:41:57,273 INFO   ep 048 loss 0.2228 val_macro_f1 0.6994
2026-09-25 18:41:58,204 INFO   ep 049 loss 0.5024 val_macro_f1 0.6900
2026-09-25 18:41:59,115 INFO   ep 050 loss 0.3428 val_macro_f1 0.6968
2026-09-25 18:42:00,020 INFO   ep 051 loss 0.3041 val_macro_f1 0.7022
2026-09-25 18:42:00,957 INFO   ep 052 loss 0.2318 val_macro_f1 0.7026
2026-09-25 18:42:01,902 INFO   ep 053 loss 0.2894 val_macro_f1 0.6992
2026-09-25 18:42:02,797 INFO   ep 054 loss 0.3074 val_macro_f1 0.6982
2026-09-25 18:42:03,662 INFO   ep 055 loss 0.2417 val_macro_f1 0.7039
2026-09-25 18:42:04,575 INFO   ep 056 loss 1.3554 val_macro_f1 0.6914
2026-09-25 18:42:05,419 INFO   ep 057 loss 0.2504 val_macro_f1 0.6982
2026-09-25 18:42:06,334 INFO   ep 058 loss 0.1223 val_macro_f1 0.6976
2026-09-25 18:42:07,202 INFO   ep 059 loss 0.2464 val_macro_f1 0.6940
2026-09-25 18:42:08,061 INFO   ep 060 loss 0.1801 val_macro_f1 0.6877
2026-09-25 18:42:08,931 INFO   ep 061 loss 0.2098 val_macro_f1 0.6952
2026-09-25 18:42:09,852 INFO   ep 062 loss 0.1928 val_macro_f1 0.7081
2026-09-25 18:42:10,743 INFO   ep 063 loss 0.1414 val_macro_f1 0.6954
2026-09-25 18:42:11,611 INFO   ep 064 loss 0.1306 val_macro_f1 0.7021
2026-09-25 18:42:12,462 INFO   ep 065 loss 0.1476 val_macro_f1 0.6876
2026-09-25 18:42:13,354 INFO   ep 066 loss 0.2606 val_macro_f1 0.6835
2026-09-25 18:42:14,242 INFO   ep 067 loss 0.1811 val_macro_f1 0.6908
2026-09-25 18:42:15,137 INFO   ep 068 loss 0.0714 val_macro_f1 0.7035
2026-09-25 18:42:16,062 INFO   ep 069 loss 0.1345 val_macro_f1 0.7048
2026-09-25 18:42:16,943 INFO   ep 070 loss 0.1482 val_macro_f1 0.7001
2026-09-25 18:42:17,795 INFO   ep 071 loss 0.1122 val_macro_f1 0.7013
2026-09-25 18:42:18,660 INFO   ep 072 loss 0.2644 val_macro_f1 0.6981
2026-09-25 18:42:19,564 INFO   ep 073 loss 0.1198 val_macro_f1 0.7040
2026-09-25 18:42:20,436 INFO   ep 074 loss 0.1215 val_macro_f1 0.7003
2026-09-25 18:42:21,281 INFO   ep 075 loss 0.1141 val_macro_f1 0.7012
2026-09-25 18:42:22,134 INFO   ep 076 loss 0.1422 val_macro_f1 0.6965
2026-09-25 18:42:22,958 INFO   ep 077 loss 0.1512 val_macro_f1 0.6973
2026-09-25 18:42:23,788 INFO   ep 078 loss 0.1588 val_macro_f1 0.6981
2026-09-25 18:42:24,648 INFO   ep 079 loss 0.5257 val_macro_f1 0.7050
2026-09-25 18:42:25,533 INFO   ep 080 loss 0.1507 val_macro_f1 0.7001
2026-09-25 18:42:26,367 INFO   ep 081 loss 0.3087 val_macro_f1 0.7048
2026-09-25 18:42:27,245 INFO   ep 082 loss 0.0979 val_macro_f1 0.7086
2026-09-25 18:42:28,115 INFO   ep 083 loss 0.1262 val_macro_f1 0.6986
2026-09-25 18:42:29,006 INFO   ep 084 loss 0.2518 val_macro_f1 0.7099 *
2026-09-25 18:42:29,900 INFO   ep 085 loss 0.1859 val_macro_f1 0.6989
2026-09-25 18:42:30,746 INFO   ep 086 loss 0.1647 val_macro_f1 0.7032
2026-09-25 18:42:31,563 INFO   ep 087 loss 0.1021 val_macro_f1 0.7047
2026-09-25 18:42:32,381 INFO   ep 088 loss 0.2144 val_macro_f1 0.7040
2026-09-25 18:42:33,200 INFO   ep 089 loss 0.1459 val_macro_f1 0.7008
2026-09-25 18:42:34,061 INFO   ep 090 loss 0.0797 val_macro_f1 0.7033
2026-09-25 18:42:34,923 INFO   ep 091 loss 0.3273 val_macro_f1 0.7023
2026-09-25 18:42:35,781 INFO   ep 092 loss 0.1047 val_macro_f1 0.7001
2026-09-25 18:42:36,657 INFO   ep 093 loss 0.2225 val_macro_f1 0.7016
2026-09-25 18:42:37,491 INFO   ep 094 loss 0.0889 val_macro_f1 0.7068
2026-09-25 18:42:38,320 INFO   ep 095 loss 0.0745 val_macro_f1 0.7075
2026-09-25 18:42:39,179 INFO   ep 096 loss 0.0645 val_macro_f1 0.7102 *
2026-09-25 18:42:40,066 INFO   ep 097 loss 0.2553 val_macro_f1 0.7080
2026-09-25 18:42:40,920 INFO   ep 098 loss 0.2062 val_macro_f1 0.7031
2026-09-25 18:42:41,792 INFO   ep 099 loss 0.3572 val_macro_f1 0.7026
2026-09-25 18:42:42,646 INFO   ep 100 loss 0.0573 val_macro_f1 0.7020
2026-09-25 18:42:43,512 INFO   ep 101 loss 0.1699 val_macro_f1 0.7049
2026-09-25 18:42:44,339 INFO   ep 102 loss 0.0521 val_macro_f1 0.7063
2026-09-25 18:42:45,179 INFO   ep 103 loss 0.1846 val_macro_f1 0.7036
2026-09-25 18:42:46,021 INFO   ep 104 loss 0.0492 val_macro_f1 0.7060
2026-09-25 18:42:46,838 INFO   ep 105 loss 0.1455 val_macro_f1 0.7056
2026-09-25 18:42:47,644 INFO   ep 106 loss 0.1384 val_macro_f1 0.7092
2026-09-25 18:42:48,478 INFO   ep 107 loss 0.2305 val_macro_f1 0.7042
2026-09-25 18:42:49,443 INFO   ep 108 loss 0.1562 val_macro_f1 0.7062
2026-09-25 18:42:50,372 INFO   ep 109 loss 0.0681 val_macro_f1 0.7057
2026-09-25 18:42:51,242 INFO   ep 110 loss 0.0799 val_macro_f1 0.7040
2026-09-25 18:42:52,113 INFO   ep 111 loss 0.1289 val_macro_f1 0.7042
2026-09-25 18:42:53,000 INFO   ep 112 loss 0.2486 val_macro_f1 0.7034
2026-09-25 18:42:53,893 INFO   ep 113 loss 0.1453 val_macro_f1 0.7059
2026-09-25 18:42:54,775 INFO   ep 114 loss 0.0502 val_macro_f1 0.7049
2026-09-25 18:42:55,646 INFO   ep 115 loss 0.0779 val_macro_f1 0.7056
2026-09-25 18:42:56,545 INFO   ep 116 loss 0.1438 val_macro_f1 0.7048
2026-09-25 18:42:57,431 INFO   ep 117 loss 0.1151 val_macro_f1 0.7049
2026-09-25 18:42:58,304 INFO   ep 118 loss 0.1127 val_macro_f1 0.7052
2026-09-25 18:42:59,167 INFO   ep 119 loss 0.1113 val_macro_f1 0.7051
2026-09-25 18:42:59,236 INFO seed1 F_post attention: averaged rho=-0.378
2026-09-25 18:43:00,175 INFO   ep 000 loss 1.6631 val_macro_f1 0.5503 *
2026-09-25 18:43:01,053 INFO   ep 001 loss 0.9253 val_macro_f1 0.6191 *
2026-09-25 18:43:01,911 INFO   ep 002 loss 1.4884 val_macro_f1 0.6260 *
2026-09-25 18:43:02,781 INFO   ep 003 loss 0.8946 val_macro_f1 0.6414 *
2026-09-25 18:43:03,638 INFO   ep 004 loss 0.6924 val_macro_f1 0.6261
2026-09-25 18:43:04,506 INFO   ep 005 loss 1.2248 val_macro_f1 0.6258
2026-09-25 18:43:05,368 INFO   ep 006 loss 0.8544 val_macro_f1 0.6181
2026-09-25 18:43:06,256 INFO   ep 007 loss 0.5312 val_macro_f1 0.6644 *
2026-09-25 18:43:07,116 INFO   ep 008 loss 0.9926 val_macro_f1 0.6565
2026-09-25 18:43:07,998 INFO   ep 009 loss 0.7036 val_macro_f1 0.6747 *
2026-09-25 18:43:08,867 INFO   ep 010 loss 0.9607 val_macro_f1 0.6835 *
2026-09-25 18:43:09,735 INFO   ep 011 loss 0.6473 val_macro_f1 0.6710
2026-09-25 18:43:10,590 INFO   ep 012 loss 0.6125 val_macro_f1 0.6811
2026-09-25 18:43:11,439 INFO   ep 013 loss 0.6318 val_macro_f1 0.6798
2026-09-25 18:43:12,306 INFO   ep 014 loss 0.6545 val_macro_f1 0.6995 *
2026-09-25 18:43:13,134 INFO   ep 015 loss 0.5384 val_macro_f1 0.6871
2026-09-25 18:43:13,963 INFO   ep 016 loss 0.4087 val_macro_f1 0.6862
2026-09-25 18:43:14,813 INFO   ep 017 loss 0.5686 val_macro_f1 0.6793
2026-09-25 18:43:15,713 INFO   ep 018 loss 1.1306 val_macro_f1 0.7041 *
2026-09-25 18:43:16,562 INFO   ep 019 loss 1.0532 val_macro_f1 0.6764
2026-09-25 18:43:17,442 INFO   ep 020 loss 0.5074 val_macro_f1 0.7072 *
2026-09-25 18:43:18,312 INFO   ep 021 loss 0.3621 val_macro_f1 0.6965
2026-09-25 18:43:19,312 INFO   ep 022 loss 0.5291 val_macro_f1 0.7023
2026-09-25 18:43:20,191 INFO   ep 023 loss 0.5448 val_macro_f1 0.6920
2026-09-25 18:43:21,112 INFO   ep 024 loss 0.4264 val_macro_f1 0.7063
2026-09-25 18:43:21,960 INFO   ep 025 loss 0.4309 val_macro_f1 0.7005
2026-09-25 18:43:22,792 INFO   ep 026 loss 0.9650 val_macro_f1 0.7012
2026-09-25 18:43:23,622 INFO   ep 027 loss 0.9644 val_macro_f1 0.7021
2026-09-25 18:43:24,492 INFO   ep 028 loss 0.7008 val_macro_f1 0.6985
2026-09-25 18:43:25,329 INFO   ep 029 loss 0.4239 val_macro_f1 0.7050
2026-09-25 18:43:26,191 INFO   ep 030 loss 0.4907 val_macro_f1 0.7022
2026-09-25 18:43:27,073 INFO   ep 031 loss 0.3495 val_macro_f1 0.7115 *
2026-09-25 18:43:27,914 INFO   ep 032 loss 0.4458 val_macro_f1 0.7061
2026-09-25 18:43:28,780 INFO   ep 033 loss 0.6958 val_macro_f1 0.6998
2026-09-25 18:43:29,643 INFO   ep 034 loss 0.7414 val_macro_f1 0.6987
2026-09-25 18:43:30,518 INFO   ep 035 loss 0.5668 val_macro_f1 0.7136 *
2026-09-25 18:43:31,365 INFO   ep 036 loss 1.5112 val_macro_f1 0.7052
2026-09-25 18:43:32,205 INFO   ep 037 loss 0.3388 val_macro_f1 0.6874
2026-09-25 18:43:33,029 INFO   ep 038 loss 0.4815 val_macro_f1 0.6983
2026-09-25 18:43:33,846 INFO   ep 039 loss 0.6172 val_macro_f1 0.7067
2026-09-25 18:43:34,730 INFO   ep 040 loss 0.4775 val_macro_f1 0.6967
2026-09-25 18:43:35,546 INFO   ep 041 loss 0.6714 val_macro_f1 0.6999

    layer  head      mean       min       max  consistent_sign
1       0     1  0.080223 -0.005537  0.229528            False
6       1     2 -0.001139 -0.262474  0.145933            False
0       0     0 -0.040875 -0.132878  0.060287            False
10      2     2 -0.076304 -0.108749 -0.011552             True
3       0     3 -0.077102 -0.441490  0.132604            False
2       0     2 -0.091091 -0.165003 -0.001230             True
11      2     3 -0.122465 -0.393575  0.247437            False
7       1     3 -0.144931 -0.318592  0.082502            False
4       1     0 -0.169036 -0.330759 -0.013055             True
8       2     0 -0.232126 -0.362406 -0.149146             True
5       1     1 -0.360857 -0.442857 -0.292891             True
9       2     1 -0.459991 -0.708407 -0.320437             True

In [5]:
Y = lab.set_index('contractID')[scvd.LABELS]
tl = tools.set_index('contractID')
if tl.index.duplicated().any():
    tl = tl[~tl.index.duplicated(keep='first')]
tl = tl.reindex(Y.index)
tool_cols = {j: [c for c in tl.columns if c.endswith(f'_{j+1}')] for j in range(8)}
agree = pd.DataFrame(True, index=Y.index, columns=scvd.LABELS)
for j, col in enumerate(scvd.LABELS):
    tc = tl[tool_cols[j]]
    obs = tc.notna()
    vals = tc.fillna(-1).eq(Y[col].values[:, None] * 1.0).where(obs, True)
    agree[col] = vals.all(1)
uncontested = agree.all(1)
log.info('uncontested contracts: %d (%.1f%%)', uncontested.sum(), 100 * uncontested.mean())

# R2#4: class balance of the uncontested subset
unc_prev = Y.loc[uncontested].mean().to_dict()
unc_all_neg = float((Y.loc[uncontested].sum(1) == 0).mean())
log.info('uncontested per-label positive rate: %s', {k: round(v, 4) for k, v in unc_prev.items()})
log.info('uncontested all-negative fraction: %.4f', unc_all_neg)

maj = pd.DataFrame(np.nan, index=Y.index, columns=scvd.LABELS)
for j, col in enumerate(scvd.LABELS):
    tc = tl[tool_cols[j]]
    s = tc.sum(1); n = tc.notna().sum(1)
    maj[col] = np.where(n > 0, (s / n.clip(lower=1) > 0.5).astype(float), np.nan)
maj = maj.fillna(Y.astype(float))

res_runs = []
ids_te = d['ids_te']
for name, mdl_factory in [('LGC', lambda: scvd.LGC(d['fams'], M, dm=128, tau=0.2)),
                          ('LAT', lambda: scvd.LAT(d['fams'], dm=128, layers=3)),
                          ('BR-trunk', lambda: scvd.LAT(d['fams'], dm=128, layers=3, trunk_only=True))]:
    for seed in SEEDS:                                     # R1#2: was single-seed
        scvd.set_seed(seed)   # was np.random.seed(seed) -- didn't touch torch's RNG at all
        mdl = mdl_factory(); pt, _h = scvd.train_torch(mdl, d, cfg, log)
        th = scvd.tune_thresholds(d['y_va'], scvd.predict(mdl, d, 'va'))
        pred = (pt >= th).astype(int)
        yte = d['y_te']
        m_full = scvd.all_metrics(yte, pred, pt)

        mask = uncontested.reindex(ids_te).to_numpy()
        m_ag = scvd.all_metrics(yte[mask], pred[mask], pt[mask])

        ymaj = maj.reindex(ids_te)[scvd.LABELS].to_numpy(int)
        d2 = dict(d)
        d2['y_tr'] = maj.reindex(d['ids_tr'])[scvd.LABELS].to_numpy(int)
        d2['y_va'] = maj.reindex(d['ids_va'])[scvd.LABELS].to_numpy(int)
        d2['y_te'] = ymaj
        scvd.set_seed(seed)   # was np.random.seed(seed) -- didn't touch torch's RNG at all
        mdl2 = mdl_factory(); pt2, _h2 = scvd.train_torch(mdl2, d2, cfg, log)
        # R1#3: threshold-tune the majority-vote arm on its own held-out
        # validation split instead of a fixed 0.5 cut
        th2 = scvd.tune_thresholds(d2['y_va'], scvd.predict(mdl2, d2, 'va'))
        m_maj = scvd.all_metrics(ymaj, (pt2 >= th2).astype(int), pt2)

        for arm, m in [('full', m_full), ('agreement', m_ag), ('majority', m_maj)]:
            res_runs.append({'model': name, 'arm': arm, 'seed': seed,
                              'macro_f1': m['macro_f1'], 'macro_auc': m['macro_auc']})
        log.info('%-9s seed%d full=%.4f unc=%.4f maj(tuned)=%.4f | '
                 'full_auc=%.4f unc_auc=%.4f maj_auc=%.4f',
                 name, seed, m_full['macro_f1'], m_ag['macro_f1'], m_maj['macro_f1'],
                 m_full['macro_auc'], m_ag['macro_auc'], m_maj['macro_auc'])

res_df = pd.DataFrame(res_runs)
res_summary = (res_df.groupby(['model', 'arm'])[['macro_f1', 'macro_auc']]
               .agg(['mean', 'min', 'max']))
res_summary.columns = ['_'.join(c) for c in res_summary.columns]
res_summary = res_summary.reset_index()

res = {'per_seed': res_runs, 'summary': res_summary.to_dict(orient='records'),
       'uncontested_prevalence': unc_prev, 'uncontested_all_negative_fraction': unc_all_neg,
       'n_seeds': list(SEEDS)}
json.dump(res, open(f'{root}/results/stage5_robustness.json', 'w'), indent=1)
res_df.to_csv(f'{root}/results/stage5_robustness_per_seed.csv', index=False)

res_mean = {m: {arm: float(res_df[(res_df.model == m) & (res_df.arm == arm)]['macro_f1'].mean())
                for arm in ['full', 'agreement', 'majority']}
            for m in res_df['model'].unique()}
scvd.plot_robustness(res_mean, root, log)
res_summary

2026-09-25 18:44:43,493 INFO uncontested contracts: 2361 (10.6%)
2026-09-25 18:44:43,498 INFO uncontested per-label positive rate: {'Reentrancy': 0.0089, 'Access Control': 0.008, 'Arithmetic': 0.0021, 'Unchecked Return Values': 0.0025, 'DoS': 0.0021, 'Bad Randomness': 0.0008, 'Front Running': 0.0008, 'Time manipulation': 0.0034}
2026-09-25 18:44:43,498 INFO uncontested all-negative fraction: 0.9835
2026-09-25 18:44:43,991 INFO   ep 000 loss 2.4017 val_macro_f1 0.3842 *
2026-09-25 18:44:44,383 INFO   ep 001 loss 1.5038 val_macro_f1 0.3907 *
2026-09-25 18:44:44,774 INFO   ep 002 loss 2.0974 val_macro_f1 0.2988
2026-09-25 18:44:45,169 INFO   ep 003 loss 1.0621 val_macro_f1 0.4838 *
2026-09-25 18:44:45,602 INFO   ep 004 loss 0.8996 val_macro_f1 0.4163
2026-09-25 18:44:46,017 INFO   ep 005 loss 0.9119 val_macro_f1 0.5580 *
2026-09-25 18:44:46,455 INFO   ep 006 loss 0.7086 val_macro_f1 0.5089
2026-09-25 18:44:46,861 INFO   ep 007 loss 0.6563 val_macro_f1 0.5651 *
2026-09-25 18:44:47,261 INFO   ep 008 loss 0.8075 val_macro_f1 0.5016
2026-09-25 18:44:47,668 INFO   ep 009 loss 1.1201 val_macro_f1 0.6134 *
2026-09-25 18:44:48,074 INFO   ep 010 loss 1.7883 val_macro_f1 0.6332 *
2026-09-25 18:44:48,471 INFO   ep 011 loss 0.8484 val_macro_f1 0.6065
2026-09-25 18:44:48,875 INFO   ep 012 loss 0.7043 val_macro_f1 0.5688
2026-09-25 18:44:49,305 INFO   ep 013 loss 0.5732 val_macro_f1 0.6429 *
2026-09-25 18:44:49,744 INFO   ep 014 loss 0.7435 val_macro_f1 0.6459 *
2026-09-25 18:44:50,154 INFO   ep 015 loss 0.7426 val_macro_f1 0.6129
2026-09-25 18:44:50,553 INFO   ep 016 loss 0.4199 val_macro_f1 0.5514
2026-09-25 18:44:50,978 INFO   ep 017 loss 0.7901 val_macro_f1 0.6621 *
2026-09-25 18:44:51,373 INFO   ep 018 loss 0.5638 val_macro_f1 0.6411
2026-09-25 18:44:51,767 INFO   ep 019 loss 0.6562 val_macro_f1 0.6851 *
2026-09-25 18:44:52,160 INFO   ep 020 loss 0.5636 val_macro_f1 0.6809
2026-09-25 18:44:52,561 INFO   ep 021 loss 0.6220 val_macro_f1 0.7235 *
2026-09-25 18:44:52,949 INFO   ep 022 loss 0.4719 val_macro_f1 0.6811
2026-09-25 18:44:53,336 INFO   ep 023 loss 0.3744 val_macro_f1 0.7152
2026-09-25 18:44:53,712 INFO   ep 024 loss 0.4847 val_macro_f1 0.6769
2026-09-25 18:44:54,114 INFO   ep 025 loss 0.5213 val_macro_f1 0.7349 *
2026-09-25 18:44:54,559 INFO   ep 026 loss 0.3724 val_macro_f1 0.7444 *
2026-09-25 18:44:55,000 INFO   ep 027 loss 0.4902 val_macro_f1 0.7383
2026-09-25 18:44:55,400 INFO   ep 028 loss 0.1792 val_macro_f1 0.7132
2026-09-25 18:44:55,800 INFO   ep 029 loss 0.4439 val_macro_f1 0.7334
2026-09-25 18:44:56,194 INFO   ep 030 loss 0.3272 val_macro_f1 0.7371
2026-09-25 18:44:56,582 INFO   ep 031 loss 0.2546 val_macro_f1 0.7383
2026-09-25 18:44:56,970 INFO   ep 032 loss 0.2916 val_macro_f1 0.7462 *
2026-09-25 18:44:57,359 INFO   ep 033 loss 0.4387 val_macro_f1 0.7447
2026-09-25 18:44:57,756 INFO   ep 034 loss 0.3857 val_macro_f1 0.7373
2026-09-25 18:44:58,157 INFO   ep 035 loss 0.6249 val_macro_f1 0.7431
2026-09-25 18:44:58,550 INFO   ep 036 loss 0.2159 val_macro_f1 0.7027
2026-09-25 18:44:58,957 INFO   ep 037 loss 0.2485 val_macro_f1 0.7496 *
2026-09-25 18:44:59,364 INFO   ep 038 loss 0.2507 val_macro_f1 0.7292
2026-09-25 18:44:59,799 INFO   ep 039 loss 0.2494 val_macro_f1 0.7571 *
2026-09-25 18:45:00,205 INFO   ep 040 loss 0.1657 val_macro_f1 0.7450
2026-09-25 18:45:00,607 INFO   ep 041 loss 0.1704 val_macro_f1 0.7584 *
2026-09-25 18:45:00,995 INFO   ep 042 loss 0.1499 val_macro_f1 0.7542
2026-09-25 18:45:01,377 INFO   ep 043 loss 0.1727 val_macro_f1 0.7579
2026-09-25 18:45:01,757 INFO   ep 044 loss 0.1524 val_macro_f1 0.7545
2026-09-25 18:45:02,151 INFO   ep 045 loss 0.1708 val_macro_f1 0.7579
2026-09-25 18:45:02,574 INFO   ep 046 loss 0.1732 val_macro_f1 0.7596 *
2026-09-25 18:45:03,004 INFO   ep 047 loss 0.1709 val_macro_f1 0.7600 *
2026-09-25 18:45:03,443 INFO   ep 048 loss 0.1366 val_macro_f1 0.7583
2026-09-25 18:45:03,870 INFO   ep 049 loss 0.1230 val_macro_f1 0.7562
2026-09-25 18:45:04,294 INFO   ep 050 loss 0.1068 val_macro_f1 0.7449
2026-09-25 18:45:04,724 INFO   ep 051 loss 0.1856 val_macro_f1 0.7551
2026-09-25 18:45:05,150 INFO   ep 052 loss 0.0890 val_macro_f1 0.7475
2026-09-25 18:45:05,534 INFO   ep 053 loss 0.1249 val_macro_f1 0.7559
2026-09-25 18:45:05,929 INFO   ep 054 loss 0.1359 val_macro_f1 0.7553
2026-09-25 18:45:06,312 INFO   ep 055 loss 0.1021 val_macro_f1 0.7547
2026-09-25 18:45:06,736 INFO   ep 056 loss 0.0673 val_macro_f1 0.7432
2026-09-25 18:45:07,154 INFO   ep 057 loss 0.1073 val_macro_f1 0.7512
2026-09-25 18:45:07,538 INFO   ep 058 loss 0.0876 val_macro_f1 0.7391
2026-09-25 18:45:07,931 INFO   ep 059 loss 0.1361 val_macro_f1 0.7463
2026-09-25 18:45:08,327 INFO   ep 060 loss 0.0951 val_macro_f1 0.7573
2026-09-25 18:45:08,719 INFO   ep 061 loss 0.0648 val_macro_f1 0.7541
2026-09-25 18:45:09,119 INFO   ep 062 loss 0.1011 val_macro_f1 0.7460
2026-09-25 18:45:09,543 INFO   ep 063 loss 0.0597 val_macro_f1 0.7547
2026-09-25 18:45:09,971 INFO   ep 064 loss 0.0561 val_macro_f1 0.7569
2026-09-25 18:45:10,372 INFO   ep 065 loss 0.1130 val_macro_f1 0.7507
2026-09-25 18:45:10,769 INFO   ep 066 loss 0.1075 val_macro_f1 0.7542
2026-09-25 18:45:11,169 INFO   ep 067 loss 0.0911 val_macro_f1 0.7591
2026-09-25 18:45:11,558 INFO   ep 068 loss 0.0488 val_macro_f1 0.7580
2026-09-25 18:45:11,945 INFO   ep 069 loss 0.0960 val_macro_f1 0.7607 *
2026-09-25 18:45:12,336 INFO   ep 070 loss 0.0966 val_macro_f1 0.7538
2026-09-25 18:45:12,715 INFO   ep 071 loss 0.0635 val_macro_f1 0.7555
2026-09-25 18:45:13,094 INFO   ep 072 loss 0.0601 val_macro_f1 0.7512
2026-09-25 18:45:13,499 INFO   ep 073 loss 0.0619 val_macro_f1 0.7552
2026-09-25 18:45:13,871 INFO   ep 074 loss 0.0550 val_macro_f1 0.7560
2026-09-25 18:45:14,249 INFO   ep 075 loss 0.0538 val_macro_f1 0.7535
2026-09-25 18:45:14,628 INFO   ep 076 loss 0.0589 val_macro_f1 0.7557
2026-09-25 18:45:14,996 INFO   ep 077 loss 0.0424 val_macro_f1 0.7572
2026-09-25 18:45:15,365 INFO   ep 078 loss 0.0380 val_macro_f1 0.7547
2026-09-25 18:45:15,758 INFO   ep 079 loss 0.0565 val_macro_f1 0.7536
2026-09-25 18:45:16,165 INFO   ep 080 loss 0.0547 val_macro_f1 0.7528
2026-09-25 18:45:16,571 INFO   ep 081 loss 0.0483 val_macro_f1 0.7537
2026-09-25 18:45:16,983 INFO   ep 082 loss 0.0427 val_macro_f1 0.7531
2026-09-25 18:45:17,387 INFO   ep 083 loss 0.0372 val_macro_f1 0.7529
2026-09-25 18:45:17,755 INFO   ep 084 loss 0.0398 val_macro_f1 0.7514
2026-09-25 18:45:18,123 INFO   ep 085 loss 0.0574 val_macro_f1 0.7521
2026-09-25 18:45:18,494 INFO   ep 086 loss 0.0491 val_macro_f1 0.7556
2026-09-25 18:45:18,864 INFO   ep 087 loss 0.0585 val_macro_f1 0.7538
2026-09-25 18:45:19,244 INFO   ep 088 loss 0.0372 val_macro_f1 0.7513
2026-09-25 18:45:19,652 INFO   ep 089 loss 0.0476 val_macro_f1 0.7515
2026-09-25 18:45:20,034 INFO   ep 090 loss 0.0451 val_macro_f1 0.7541
2026-09-25 18:45:20,401 INFO   ep 091 loss 0.0565 val_macro_f1 0.7516
2026-09-25 18:45:20,769 INFO   ep 092 loss 0.0337 val_macro_f1 0.7503
2026-09-25 18:45:21,151 INFO   ep 093 loss 0.0341 val_macro_f1 0.7516
2026-09-25 18:45:21,532 INFO   ep 094 loss 0.0455 val_macro_f1 0.7484
2026-09-25 18:45:21,909 INFO   ep 095 loss 0.0477 val_macro_f1 0.7532
2026-09-25 18:45:22,278 INFO   ep 096 loss 0.0307 val_macro_f1 0.7506
2026-09-25 18:45:22,641 INFO   ep 097 loss 0.0318 val_macro_f1 0.7493
2026-09-25 18:45:23,010 INFO   ep 098 loss 0.0473 val_macro_f1 0.7494
2026-09-25 18:45:23,381 INFO   ep 099 loss 0.0497 val_macro_f1 0.7500
2026-09-25 18:45:23,758 INFO   ep 100 loss 0.0280 val_macro_f1 0.7504
2026-09-25 18:45:24,141 INFO   ep 101 loss 0.0546 val_macro_f1 0.7495
2026-09-25 18:45:24,518 INFO   ep 102 loss 0.0349 val_macro_f1 0.7520
2026-09-25 18:45:24,901 INFO   ep 103 loss 0.0471 val_macro_f1 0.7480
2026-09-25 18:45:25,281 INFO   ep 104 loss 0.0275 val_macro_f1 0.7512
2026-09-25 18:45:25,664 INFO   ep 105 loss 0.0306 val_macro_f1 0.7477
2026-09-25 18:45:26,048 INFO   ep 106 loss 0.0342 val_macro_f1 0.7477
2026-09-25 18:45:26,490 INFO   ep 107 loss 0.0453 val_macro_f1 0.7498
2026-09-25 18:45:26,910 INFO   ep 108 loss 0.0461 val_macro_f1 0.7464
2026-09-25 18:45:27,334 INFO   ep 109 loss 0.0322 val_macro_f1 0.7488
2026-09-25 18:45:27,765 INFO   ep 110 loss 0.0335 val_macro_f1 0.7484
2026-09-25 18:45:28,177 INFO   ep 111 loss 0.0380 val_macro_f1 0.7478
2026-09-25 18:45:28,587 INFO   ep 112 loss 0.0344 val_macro_f1 0.7470
2026-09-25 18:45:29,002 INFO   ep 113 loss 0.0264 val_macro_f1 0.7470
2026-09-25 18:45:29,398 INFO   ep 114 loss 0.0363 val_macro_f1 0.7466
2026-09-25 18:45:29,820 INFO   ep 115 loss 0.0379 val_macro_f1 0.7468
2026-09-25 18:45:30,203 INFO   ep 116 loss 0.0447 val_macro_f1 0.7471
2026-09-25 18:45:30,584 INFO   ep 117 loss 0.0261 val_macro_f1 0.7467
2026-09-25 18:45:30,971 INFO   ep 118 loss 0.0282 val_macro_f1 0.7468
2026-09-25 18:45:31,360 INFO   ep 119 loss 0.0518 val_macro_f1 0.7468
2026-09-25 18:45:31,812 INFO   ep 000 loss 3.4135 val_macro_f1 0.0000 *
2026-09-25 18:45:32,189 INFO   ep 001 loss 3.2215 val_macro_f1 0.0000 *
2026-09-25 18:45:32,564 INFO   ep 002 loss 4.2770 val_macro_f1 0.0071 *
2026-09-25 18:45:32,959 INFO   ep 003 loss 4.1903 val_macro_f1 0.0080 *
2026-09-25 18:45:33,355 INFO   ep 004 loss 4.2757 val_macro_f1 0.0424 *
2026-09-25 18:45:33,749 INFO   ep 005 loss 0.8119 val_macro_f1 0.0380
2026-09-25 18:45:34,146 INFO   ep 006 loss 3.0293 val_macro_f1 0.0583 *
2026-09-25 18:45:34,531 INFO   ep 007 loss 0.8626 val_macro_f1 0.0666 *
2026-09-25 18:45:34,914 INFO   ep 008 loss 2.5062 val_macro_f1 0.1371 *
2026-09-25 18:45:35,286 INFO   ep 009 loss 1.0933 val_macro_f1 0.0140
2026-09-25 18:45:35,673 INFO   ep 010 loss 2.0892 val_macro_f1 0.0377
2026-09-25 18:45:36,041 INFO   ep 011 loss 0.9551 val_macro_f1 0.0860
2026-09-25 18:45:36,428 INFO   ep 012 loss 2.3444 val_macro_f1 0.1293
2026-09-25 18:45:36,819 INFO   ep 013 loss 2.1442 val_macro_f1 0.3759 *
2026-09-25 18:45:37,205 INFO   ep 014 loss 0.6633 val_macro_f1 0.1382
2026-09-25 18:45:37,587 INFO   ep 015 loss 1.8629 val_macro_f1 0.2299
2026-09-25 18:45:37,966 INFO   ep 016 loss 0.5687 val_macro_f1 0.2119
2026-09-25 18:45:38,342 INFO   ep 017 loss 2.0118 val_macro_f1 0.3343
2026-09-25 18:45:38,710 INFO   ep 018 loss 2.2416 val_macro_f1 0.2185
2026-09-25 18:45:39,088 INFO   ep 019 loss 2.1174 val_macro_f1 0.3216
2026-09-25 18:45:39,500 INFO   ep 020 loss 1.7983 val_macro_f1 0.4076 *
2026-09-25 18:45:39,870 INFO   ep 021 loss 0.2875 val_macro_f1 0.3490
2026-09-25 18:45:40,243 INFO   ep 022 loss 0.9540 val_macro_f1 0.3784
2026-09-25 18:45:40,614 INFO   ep 023 loss 2.3984 val_macro_f1 0.4505 *
2026-09-25 18:45:41,009 INFO   ep 024 loss 0.9653 val_macro_f1 0.3892
2026-09-25 18:45:41,397 INFO   ep 025 loss 1.9060 val_macro_f1 0.3345
2026-09-25 18:45:41,776 INFO   ep 026 loss 1.8014 val_macro_f1 0.4991 *
2026-09-25 18:45:42,157 INFO   ep 027 loss 1.2883 val_macro_f1 0.4787
2026-09-25 18:45:42,536 INFO   ep 028 loss 0.1444 val_macro_f1 0.5067 *
2026-09-25 18:45:42,911 INFO   ep 029 loss 1.0356 val_macro_f1 0.3991
2026-09-25 18:45:43,287 INFO   ep 030 loss 1.3979 val_macro_f1 0.4992
2026-09-25 18:45:43,666 INFO   ep 031 loss 1.4448 val_macro_f1 0.5325 *
2026-09-25 18:45:44,033 INFO   ep 032 loss 0.7517 val_macro_f1 0.5202
2026-09-25 18:45:44,431 INFO   ep 033 loss 1.1533 val_macro_f1 0.5283
2026-09-25 18:45:44,809 INFO   ep 034 loss 0.5686 val_macro_f1 0.5223
2026-09-25 18:45:45,181 INFO   ep 035 loss 1.9272 val_macro_f1 0.5122
2026-09-25 18:45:45,549 INFO   ep 036 loss 0.2729 val_macro_f1 0.5245
2026-09-25 18:45:45,927 INFO   ep 037 loss 0.9335 val_macro_f1 0.5308
2026-09-25 18:45:46,312 INFO   ep 038 loss 0.4071 val_macro_f1 0.5373 *
2026-09-25 18:45:46,700 INFO   ep 039 loss 0.5324 val_macro_f1 0.5435 *
2026-09-25 18:45:47,076 INFO   ep 040 loss 0.3440 val_macro_f1 0.5150
2026-09-25 18:45:47,452 INFO   ep 041 loss 0.6874 val_macro_f1 0.5361
2026-09-25 18:45:47,820 INFO   ep 042 loss 0.8931 val_macro_f1 0.5489 *
2026-09-25 18:45:48,192 INFO   ep 043 loss 1.1967 val_macro_f1 0.5305
2026-09-25 18:45:48,567 INFO   ep 044 loss 0.2083 val_macro_f1 0.5286
2026-09-25 18:45:48,938 INFO   ep 045 loss 0.2996 val_macro_f1 0.5394
2026-09-25 18:45:49,337 INFO   ep 046 loss 0.9217 val_macro_f1 0.5262
2026-09-25 18:45:49,761 INFO   ep 047 loss 0.3197 val_macro_f1 0.5193
2026-09-25 18:45:50,134 INFO   ep 048 loss 0.2757 val_macro_f1 0.5375
2026-09-25 18:45:50,519 INFO   ep 049 loss 0.3501 val_macro_f1 0.5381
2026-09-25 18:45:50,893 INFO   ep 050 loss 0.1009 val_macro_f1 0.5513 *
2026-09-25 18:45:51,282 INFO   ep 051 loss 0.2263 val_macro_f1 0.5332
2026-09-25 18:45:51,661 INFO   ep 052 loss 0.1276 val_macro_f1 0.5480
2026-09-25 18:45:52,041 INFO   ep 053 loss 0.1657 val_macro_f1 0.5474
2026-09-25 18:45:52,420 INFO   ep 054 loss 0.1885 val_macro_f1 0.5242
2026-09-25 18:45:52,803 INFO   ep 055 loss 0.1219 val_macro_f1 0.5401
2026-09-25 18:45:53,186 INFO   ep 056 loss 0.0420 val_macro_f1 0.5326
2026-09-25 18:45:53,570 INFO   ep 057 loss 0.0357 val_macro_f1 0.5373
2026-09-25 18:45:53,943 INFO   ep 058 loss 0.1405 val_macro_f1 0.5486
2026-09-25 18:45:54,326 INFO   ep 059 loss 0.0582 val_macro_f1 0.5424
2026-09-25 18:45:54,716 INFO   ep 060 loss 0.0338 val_macro_f1 0.5391
2026-09-25 18:45:55,086 INFO   ep 061 loss 0.1229 val_macro_f1 0.5436
2026-09-25 18:45:55,481 INFO   ep 062 loss 0.1682 val_macro_f1 0.5421
2026-09-25 18:45:55,859 INFO   ep 063 loss 0.1074 val_macro_f1 0.5560 *
2026-09-25 18:45:56,234 INFO   ep 064 loss 0.0582 val_macro_f1 0.5369
2026-09-25 18:45:56,633 INFO   ep 065 loss 0.0973 val_macro_f1 0.5379
2026-09-25 18:45:57,009 INFO   ep 066 loss 0.1075 val_macro_f1 0.5177
2026-09-25 18:45:57,376 INFO   ep 067 loss 0.1217 val_macro_f1 0.5469
2026-09-25 18:45:57,747 INFO   ep 068 loss 0.1094 val_macro_f1 0.5495
2026-09-25 18:45:58,122 INFO   ep 069 loss 0.1980 val_macro_f1 0.5428
2026-09-25 18:45:58,505 INFO   ep 070 loss 0.1621 val_macro_f1 0.5133
2026-09-25 18:45:58,887 INFO   ep 071 loss 0.1394 val_macro_f1 0.5486
2026-09-25 18:45:59,272 INFO   ep 072 loss 0.1517 val_macro_f1 0.5160
2026-09-25 18:45:59,682 INFO   ep 073 loss 0.1806 val_macro_f1 0.5437
2026-09-25 18:46:00,050 INFO   ep 074 loss 0.0445 val_macro_f1 0.5026
2026-09-25 18:46:00,429 INFO   ep 075 loss 0.0627 val_macro_f1 0.5427
2026-09-25 18:46:00,804 INFO   ep 076 loss 0.1775 val_macro_f1 0.5204
2026-09-25 18:46:01,173 INFO   ep 077 loss 0.0660 val_macro_f1 0.5364
2026-09-25 18:46:01,545 INFO   ep 078 loss 0.0699 val_macro_f1 0.5138
2026-09-25 18:46:01,916 INFO   ep 079 loss 0.0858 val_macro_f1 0.5449
2026-09-25 18:46:02,299 INFO   ep 080 loss 0.1179 val_macro_f1 0.5427
2026-09-25 18:46:02,672 INFO   ep 081 loss 0.0620 val_macro_f1 0.5133
2026-09-25 18:46:03,053 INFO   ep 082 loss 0.0607 val_macro_f1 0.5150
2026-09-25 18:46:03,430 INFO   ep 083 loss 0.0562 val_macro_f1 0.5070
2026-09-25 18:46:03,813 INFO   ep 084 loss 0.0626 val_macro_f1 0.5123
2026-09-25 18:46:04,198 INFO   ep 085 loss 0.0971 val_macro_f1 0.5092
2026-09-25 18:46:04,571 INFO   ep 086 loss 0.1172 val_macro_f1 0.5131
2026-09-25 18:46:04,935 INFO   ep 087 loss 0.0480 val_macro_f1 0.5379
2026-09-25 18:46:05,309 INFO   ep 088 loss 0.0622 val_macro_f1 0.5156
2026-09-25 18:46:05,683 INFO   ep 089 loss 0.0963 val_macro_f1 0.5100
2026-09-25 18:46:06,075 INFO   ep 090 loss 0.0463 val_macro_f1 0.5125
2026-09-25 18:46:06,477 INFO   ep 091 loss 0.1050 val_macro_f1 0.5375
2026-09-25 18:46:06,871 INFO   ep 092 loss 0.0551 val_macro_f1 0.5409
2026-09-25 18:46:07,250 INFO   ep 093 loss 0.0746 val_macro_f1 0.5109
2026-09-25 18:46:07,617 INFO   ep 094 loss 0.1003 val_macro_f1 0.5111
2026-09-25 18:46:07,983 INFO   ep 095 loss 0.0812 val_macro_f1 0.5134
2026-09-25 18:46:08,349 INFO   ep 096 loss 0.0322 val_macro_f1 0.5131
2026-09-25 18:46:08,722 INFO   ep 097 loss 0.0446 val_macro_f1 0.5126
2026-09-25 18:46:09,099 INFO   ep 098 loss 0.0897 val_macro_f1 0.5124
2026-09-25 18:46:09,493 INFO   ep 099 loss 0.0462 val_macro_f1 0.5085
2026-09-25 18:46:09,876 INFO   ep 100 loss 0.0160 val_macro_f1 0.5149
2026-09-25 18:46:10,251 INFO   ep 101 loss 0.0761 val_macro_f1 0.5146
2026-09-25 18:46:10,624 INFO   ep 102 loss 0.1206 val_macro_f1 0.5141
2026-09-25 18:46:10,990 INFO   ep 103 loss 0.1478 val_macro_f1 0.5124
2026-09-25 18:46:11,367 INFO   ep 104 loss 0.0312 val_macro_f1 0.5112
2026-09-25 18:46:11,747 INFO   ep 105 loss 0.0539 val_macro_f1 0.5094
2026-09-25 18:46:12,121 INFO   ep 106 loss 0.0580 val_macro_f1 0.5103
2026-09-25 18:46:12,497 INFO   ep 107 loss 0.0919 val_macro_f1 0.5104
2026-09-25 18:46:12,871 INFO   ep 108 loss 0.0811 val_macro_f1 0.5114
2026-09-25 18:46:13,245 INFO   ep 109 loss 0.0312 val_macro_f1 0.5107
2026-09-25 18:46:13,621 INFO   ep 110 loss 0.0943 val_macro_f1 0.5117
2026-09-25 18:46:13,993 INFO   ep 111 loss 0.0665 val_macro_f1 0.5117
2026-09-25 18:46:14,372 INFO   ep 112 loss 0.0578 val_macro_f1 0.5108
2026-09-25 18:46:14,752 INFO   ep 113 loss 0.0403 val_macro_f1 0.5124
2026-09-25 18:46:15,152 INFO   ep 114 loss 0.0679 val_macro_f1 0.5107
2026-09-25 18:46:15,547 INFO   ep 115 loss 0.0610 val_macro_f1 0.5120
2026-09-25 18:46:15,928 INFO   ep 116 loss 0.0486 val_macro_f1 0.5120
2026-09-25 18:46:16,306 INFO   ep 117 loss 0.0188 val_macro_f1 0.5120
2026-09-25 18:46:16,695 INFO   ep 118 loss 0.0450 val_macro_f1 0.5120
2026-09-25 18:46:17,079 INFO   ep 119 loss 0.0242 val_macro_f1 0.5120
2026-09-25 18:46:17,121 INFO LGC       seed0 full=0.7786 unc=0.2062 maj(tuned)=0.5380 | full_auc=0.9189 unc_auc=0.7713 maj_auc=0.8692
2026-09-25 18:46:17,529 INFO   ep 000 loss 2.5964 val_macro_f1 0.4113 *
2026-09-25 18:46:17,922 INFO   ep 001 loss 1.4463 val_macro_f1 0.4382 *
2026-09-25 18:46:18,310 INFO   ep 002 loss 2.0134 val_macro_f1 0.3516
2026-09-25 18:46:18,713 INFO   ep 003 loss 1.0111 val_macro_f1 0.5595 *
2026-09-25 18:46:19,097 INFO   ep 004 loss 0.7817 val_macro_f1 0.5604 *
2026-09-25 18:46:19,552 INFO   ep 005 loss 0.7321 val_macro_f1 0.5781 *
2026-09-25 18:46:19,952 INFO   ep 006 loss 0.8086 val_macro_f1 0.5367
2026-09-25 18:46:20,362 INFO   ep 007 loss 0.7451 val_macro_f1 0.4361
2026-09-25 18:46:20,783 INFO   ep 008 loss 0.6855 val_macro_f1 0.5659
2026-09-25 18:46:21,189 INFO   ep 009 loss 0.8289 val_macro_f1 0.5309
2026-09-25 18:46:21,596 INFO   ep 010 loss 1.2231 val_macro_f1 0.5575
2026-09-25 18:46:21,994 INFO   ep 011 loss 1.0620 val_macro_f1 0.6296 *
2026-09-25 18:46:22,394 INFO   ep 012 loss 0.6901 val_macro_f1 0.6033
2026-09-25 18:46:22,798 INFO   ep 013 loss 0.5615 val_macro_f1 0.6507 *
2026-09-25 18:46:23,202 INFO   ep 014 loss 0.6479 val_macro_f1 0.6079
2026-09-25 18:46:23,617 INFO   ep 015 loss 0.8216 val_macro_f1 0.6646 *
2026-09-25 18:46:24,020 INFO   ep 016 loss 0.4230 val_macro_f1 0.4459
2026-09-25 18:46:24,431 INFO   ep 017 loss 0.7788 val_macro_f1 0.6737 *
2026-09-25 18:46:24,845 INFO   ep 018 loss 0.6548 val_macro_f1 0.6659
2026-09-25 18:46:25,239 INFO   ep 019 loss 0.6682 val_macro_f1 0.6549
2026-09-25 18:46:25,636 INFO   ep 020 loss 0.6879 val_macro_f1 0.6902 *
2026-09-25 18:46:26,038 INFO   ep 021 loss 0.5522 val_macro_f1 0.7090 *
2026-09-25 18:46:26,456 INFO   ep 022 loss 0.4746 val_macro_f1 0.7210 *
2026-09-25 18:46:26,858 INFO   ep 023 loss 0.3805 val_macro_f1 0.6703
2026-09-25 18:46:27,251 INFO   ep 024 loss 0.5189 val_macro_f1 0.6981
2026-09-25 18:46:27,650 INFO   ep 025 loss 0.4737 val_macro_f1 0.7204
2026-09-25 18:46:28,059 INFO   ep 026 loss 0.5984 val_macro_f1 0.7234 *
2026-09-25 18:46:28,461 INFO   ep 027 loss 0.6774 val_macro_f1 0.7112
2026-09-25 18:46:28,869 INFO   ep 028 loss 0.2459 val_macro_f1 0.7361 *
2026-09-25 18:46:29,272 INFO   ep 029 loss 0.4074 val_macro_f1 0.7324
2026-09-25 18:46:29,721 INFO   ep 030 loss 0.3927 val_macro_f1 0.7368 *
2026-09-25 18:46:30,129 INFO   ep 031 loss 0.3092 val_macro_f1 0.7374 *
2026-09-25 18:46:30,545 INFO   ep 032 loss 0.2695 val_macro_f1 0.7368
2026-09-25 18:46:30,948 INFO   ep 033 loss 0.3044 val_macro_f1 0.7551 *
2026-09-25 18:46:31,365 INFO   ep 034 loss 0.4112 val_macro_f1 0.7347
2026-09-25 18:46:31,786 INFO   ep 035 loss 0.3184 val_macro_f1 0.7473

,model,arm,macro_f1_mean,macro_f1_min,macro_f1_max,macro_auc_mean,macro_auc_min,macro_auc_max
0,BR-trunk,agreement,0.107578,0.072890,0.174123,0.871344,0.861798,0.877963
1,BR-trunk,full,0.794802,0.789983,0.800109,0.938852,0.938541,0.939349
2,BR-trunk,majority,0.543551,0.530556,0.557970,0.893643,0.890016,0.896350
3,LAT,agreement,0.171913,0.071735,0.278879,0.917352,0.901928,0.940082
4,LAT,full,0.797484,0.796117,0.798850,0.950092,0.948896,0.951825
5,LAT,majority,0.563483,0.559351,0.568067,0.893189,0.886481,0.898524
6,LGC,agreement,0.153791,0.091949,0.206164,0.841861,0.771259,0.929561
7,LGC,full,0.772863,0.764187,0.778567,0.922660,0.918876,0.925183
8,LGC,majority,0.543414,0.537275,0.554931,0.879926,0.869237,0.891088

In [7]:
title = 'SCVD Stage 5: interpretability and robustness'  # 46 chars, under the cap
url = scvd.push_dataset(root, 'stage5_interpretability', 'scvd-stage5-interpretability', title, log)
if url:
    print('DATASET:', url)
else:
    print('push skipped (no credentials); artifacts remain under', root)

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Starting upload for file logs.zip

100%|██████████| 45.9k/45.9k [00:00<00:00, 126kB/s]

Upload successful: logs.zip (46KB)
Starting upload for file plots.zip

100%|██████████| 139k/139k [00:00<00:00, 372kB/s]

Upload successful: plots.zip (139KB)
Starting upload for file tables.zip

100%|██████████| 22.0/22.0 [00:00<00:00, 57.7B/s]

Upload successful: tables.zip (22B)
Starting upload for file results.zip

100%|██████████| 4.92k/4.92k [00:00<00:00, 13.4kB/s]

Upload successful: results.zip (5KB)
2026-09-25 19:18:45,426 INFO pushed new version -> https://www.kaggle.com/datasets/smnihalahmed/scvd-stage5-interpretability
DATASET: https://www.kaggle.com/datasets/smnihalahmed/scvd-stage5-interpretability

In [9]:
# ============================================================
# R2#3 circularity ablation -- standalone, no scvd.py edit needed
# ============================================================
import os, sys, json, numpy as np, pandas as pd

LIB = '/kaggle/input/datasets/smnihalahmed/scvd-lib'
if not os.path.isdir(LIB):
    LIB = os.environ.get('SCVD_LIB', os.path.abspath('..'))
sys.path.insert(0, LIB)
import scvd

root, log = scvd.setup_stage('stage5_circularity')
SEEDS = (0,) if scvd.quick() else scvd.RNG_SEEDS

pre, post, lab, tools = scvd.load_dive(log)
fam = scvd.family_columns(pre, post)
splits, sdf = scvd.load_splits() or (scvd.build_splits(pre, lab, 0), None)

# F_pre = code_metadata(6) + interface_source(46) + creation_opcodes(168)
# F_post = tx_metadata(10) + temporal_position(8) + runtime_opcodes(158)
# The two opcode families (326 of 396 features) are what a static analyzer itself
# parses to produce its verdict; tx_metadata/temporal_position are on-chain execution
# history none of the six tools examine. Drop the opcode families entirely and see
# whether curated-label macro-F1 survives on the 70 remaining, non-overlapping features.
EXCLUDE = ('creation_opcodes', 'runtime_opcodes')

def make_data_excluding(pre, post, lab, fam, exclude, ids_tr, ids_va, ids_te):
    """Like scvd.make_data(view='all') but with the named families dropped entirely,
    not just their columns zeroed -- zeroing would still count as a family token in
    LAT's architecture (self.k = len(fams)); this drops the key so self.k is correct."""
    keep = [n for n in (scvd.PRE_FAMS + scvd.POST_FAMS) if n not in exclude]
    vf = {n: fam[n] for n in keep}
    pre_need = [c for n in scvd.PRE_FAMS if n in vf for c in vf[n]]
    post_need = [c for n in scvd.POST_FAMS if n in vf for c in vf[n]]
    cats = {**scvd.CATS_PRE, **scvd.CATS_POST}
    src_ = {}
    if pre_need:
        src_["pre"] = {"df": pre.set_index("contractID")[pre_need], "cols": pre_need}
    if post_need:
        src_["post"] = {"df": post.set_index("contractID")[post_need], "cols": post_need}
    lab_i = lab.set_index("contractID")
    parts = {}
    for part, ids in (("tr", ids_tr), ("va", ids_va), ("te", ids_te)):
        s = set(ids)
        parts[part] = {k: v["df"][v["df"].index.isin(s)] for k, v in src_.items()}
    preps = {k: scvd.Prep(v["cols"], {c: cc for c, cc in cats.items() if c in v["cols"]})
             .fit(parts["tr"][k].reset_index()) for k, v in src_.items()}
    out = {"fams": vf}
    for part in ("tr", "va", "te"):
        A, offs = {}, {}
        blocks = []
        for k in src_:
            Ak = preps[k].transform(parts[part][k].reset_index())
            offs[k] = {c: j for j, c in enumerate(src_[k]["cols"])}
            A[k] = Ak; blocks.append(Ak)
        out["x_" + part] = {}
        for n in vf:
            k = "pre" if n in scvd.PRE_FAMS else "post"
            out["x_" + part][n] = A[k][:, [offs[k][c] for c in vf[n]]]
        out["X_" + part] = np.hstack(blocks)
        ids_p = parts[part][next(iter(src_))].index.to_numpy()
        out["ids_" + part] = ids_p
        out["y_" + part] = lab_i.loc[ids_p, scvd.LABELS].to_numpy(int)
    return out

d_noop = make_data_excluding(pre, post, lab, fam, EXCLUDE, *splits['S1'])
M_noop = scvd.cooccurrence(d_noop['y_tr'])
log.info('circularity ablation: %d features remain (of 396) -- families kept: %s',
         d_noop['X_tr'].shape[1], list(d_noop['fams']))

cfg = {'lr': 1e-3, 'dm': 128, 'layers': 3, 'tau': 0.2, 'batch': 256,
       'epochs': 60 if scvd.quick() else 120}

circ_rows = []
for name, mdl_factory in [('LGC', lambda: scvd.LGC(d_noop['fams'], M_noop, dm=128, tau=0.2)),
                          ('LAT', lambda: scvd.LAT(d_noop['fams'], dm=128, layers=3)),
                          ('BR-trunk', lambda: scvd.LAT(d_noop['fams'], dm=128, layers=3, trunk_only=True))]:
    for seed in SEEDS:
        scvd.set_seed(seed)
        mdl = mdl_factory(); pt, _h = scvd.train_torch(mdl, d_noop, cfg, log)
        th = scvd.tune_thresholds(d_noop['y_va'], scvd.predict(mdl, d_noop, 'va'))
        m = scvd.all_metrics(d_noop['y_te'], (pt >= th).astype(int), pt)
        circ_rows.append({'model': name, 'seed': seed, 'n_features': d_noop['X_tr'].shape[1],
                          'macro_f1': m['macro_f1'], 'macro_auc': m['macro_auc']})
        log.info('no-opcode %-9s seed%d macro_f1=%.4f macro_auc=%.4f',
                 name, seed, m['macro_f1'], m['macro_auc'])

circ_df = pd.DataFrame(circ_rows)
circ_df.to_csv(f'{root}/results/stage5_circularity_ablation.csv', index=False)
print(circ_df.groupby('model')[['macro_f1', 'macro_auc']].agg(['mean', 'min', 'max']).round(4))

2026-09-25 19:31:30,266 INFO stage stage5_circularity initialised at /kaggle/working/stage5_circularity
2026-09-25 19:31:31,426 INFO loaded DIVE: pre=(22330, 222) post=(22330, 177) labels=(22330, 9) tools=(26071, 49)
2026-09-25 19:31:32,353 INFO circularity ablation: 70 features remain (of 396) -- families kept: ['code_metadata', 'interface_source', 'tx_metadata', 'temporal_position']
2026-09-25 19:31:32,750 INFO   ep 000 loss 3.5213 val_macro_f1 0.2164 *
2026-09-25 19:31:33,114 INFO   ep 001 loss 1.5117 val_macro_f1 0.2508 *
2026-09-25 19:31:33,477 INFO   ep 002 loss 2.4052 val_macro_f1 0.2960 *
2026-09-25 19:31:33,843 INFO   ep 003 loss 1.2241 val_macro_f1 0.4659 *
2026-09-25 19:31:34,217 INFO   ep 004 loss 0.8811 val_macro_f1 0.4685 *
2026-09-25 19:31:34,581 INFO   ep 005 loss 1.3700 val_macro_f1 0.4174
2026-09-25 19:31:34,937 INFO   ep 006 loss 0.9158 val_macro_f1 0.4374
2026-09-25 19:31:35,319 INFO   ep 007 loss 0.8324 val_macro_f1 0.5309 *
2026-09-25 19:31:35,712 INFO   ep 008 loss 1.2164 val_macro_f1 0.4485
2026-09-25 19:31:36,074 INFO   ep 009 loss 0.9004 val_macro_f1 0.5119
2026-09-25 19:31:36,437 INFO   ep 010 loss 1.8891 val_macro_f1 0.5532 *
2026-09-25 19:31:36,798 INFO   ep 011 loss 1.0589 val_macro_f1 0.5783 *
2026-09-25 19:31:37,191 INFO   ep 012 loss 0.7886 val_macro_f1 0.4922
2026-09-25 19:31:37,562 INFO   ep 013 loss 0.8956 val_macro_f1 0.5035
2026-09-25 19:31:37,919 INFO   ep 014 loss 0.8014 val_macro_f1 0.4528
2026-09-25 19:31:38,279 INFO   ep 015 loss 1.2801 val_macro_f1 0.4936
2026-09-25 19:31:38,643 INFO   ep 016 loss 0.6274 val_macro_f1 0.5864 *
2026-09-25 19:31:39,012 INFO   ep 017 loss 0.6537 val_macro_f1 0.5350
2026-09-25 19:31:39,387 INFO   ep 018 loss 0.9890 val_macro_f1 0.5384
2026-09-25 19:31:39,790 INFO   ep 019 loss 0.8911 val_macro_f1 0.5693
2026-09-25 19:31:40,151 INFO   ep 020 loss 0.8820 val_macro_f1 0.5570
2026-09-25 19:31:40,519 INFO   ep 021 loss 0.6913 val_macro_f1 0.6219 *
2026-09-25 19:31:40,854 INFO   ep 022 loss 0.6273 val_macro_f1 0.5351
2026-09-25 19:31:41,213 INFO   ep 023 loss 1.7630 val_macro_f1 0.6088
2026-09-25 19:31:41,561 INFO   ep 024 loss 0.7231 val_macro_f1 0.6196
2026-09-25 19:31:41,925 INFO   ep 025 loss 0.7056 val_macro_f1 0.6311 *
2026-09-25 19:31:42,287 INFO   ep 026 loss 1.2600 val_macro_f1 0.6367 *
2026-09-25 19:31:42,650 INFO   ep 027 loss 1.0921 val_macro_f1 0.6656 *
2026-09-25 19:31:43,007 INFO   ep 028 loss 0.4567 val_macro_f1 0.6510
2026-09-25 19:31:43,370 INFO   ep 029 loss 0.4921 val_macro_f1 0.6706 *
2026-09-25 19:31:43,721 INFO   ep 030 loss 0.4715 val_macro_f1 0.6370
2026-09-25 19:31:44,068 INFO   ep 031 loss 0.4088 val_macro_f1 0.6802 *
2026-09-25 19:31:44,415 INFO   ep 032 loss 0.9330 val_macro_f1 0.6478
2026-09-25 19:31:44,783 INFO   ep 033 loss 0.7694 val_macro_f1 0.6437
2026-09-25 19:31:45,132 INFO   ep 034 loss 0.7260 val_macro_f1 0.6514
2026-09-25 19:31:45,510 INFO   ep 035 loss 0.3965 val_macro_f1 0.6840 *
2026-09-25 19:31:45,869 INFO   ep 036 loss 0.4690 val_macro_f1 0.6465
2026-09-25 19:31:46,250 INFO   ep 037 loss 0.4505 val_macro_f1 0.6565
2026-09-25 19:31:46,608 INFO   ep 038 loss 0.5393 val_macro_f1 0.6295
2026-09-25 19:31:46,978 INFO   ep 039 loss 0.3753 val_macro_f1 0.6802
2026-09-25 19:31:47,324 INFO   ep 040 loss 0.3582 val_macro_f1 0.6358
2026-09-25 19:31:47,680 INFO   ep 041 loss 0.3289 val_macro_f1 0.6532
2026-09-25 19:31:48,031 INFO   ep 042 loss 0.4666 val_macro_f1 0.6732
2026-09-25 19:31:48,388 INFO   ep 043 loss 0.4512 val_macro_f1 0.6877 *
2026-09-25 19:31:48,730 INFO   ep 044 loss 0.3760 val_macro_f1 0.6773
2026-09-25 19:31:49,076 INFO   ep 045 loss 0.3660 val_macro_f1 0.6657
2026-09-25 19:31:49,455 INFO   ep 046 loss 0.3954 val_macro_f1 0.6816
2026-09-25 19:31:49,825 INFO   ep 047 loss 0.3931 val_macro_f1 0.6831
2026-09-25 19:31:50,199 INFO   ep 048 loss 0.3001 val_macro_f1 0.6703
2026-09-25 19:31:50,557 INFO   ep 049 loss 0.3410 val_macro_f1 0.6703
2026-09-25 19:31:50,904 INFO   ep 050 loss 0.2330 val_macro_f1 0.6703
2026-09-25 19:31:51,256 INFO   ep 051 loss 0.5770 val_macro_f1 0.6906 *
2026-09-25 19:31:51,629 INFO   ep 052 loss 0.2638 val_macro_f1 0.6783
2026-09-25 19:31:51,979 INFO   ep 053 loss 0.3897 val_macro_f1 0.6974 *
2026-09-25 19:31:52,364 INFO   ep 054 loss 0.2500 val_macro_f1 0.6713
2026-09-25 19:31:52,699 INFO   ep 055 loss 0.3200 val_macro_f1 0.6962
2026-09-25 19:31:53,038 INFO   ep 056 loss 0.2306 val_macro_f1 0.6775
2026-09-25 19:31:53,377 INFO   ep 057 loss 0.4043 val_macro_f1 0.6917
2026-09-25 19:31:53,701 INFO   ep 058 loss 0.2910 val_macro_f1 0.6945
2026-09-25 19:31:54,031 INFO   ep 059 loss 0.3172 val_macro_f1 0.6980 *
2026-09-25 19:31:54,392 INFO   ep 060 loss 0.3015 val_macro_f1 0.6982 *
2026-09-25 19:31:54,756 INFO   ep 061 loss 0.1858 val_macro_f1 0.6842
2026-09-25 19:31:55,122 INFO   ep 062 loss 0.3042 val_macro_f1 0.6772
2026-09-25 19:31:55,476 INFO   ep 063 loss 0.2786 val_macro_f1 0.6990 *
2026-09-25 19:31:55,870 INFO   ep 064 loss 0.3569 val_macro_f1 0.6931
2026-09-25 19:31:56,255 INFO   ep 065 loss 0.2664 val_macro_f1 0.6965
2026-09-25 19:31:56,644 INFO   ep 066 loss 0.4576 val_macro_f1 0.7037 *
2026-09-25 19:31:57,016 INFO   ep 067 loss 0.2715 val_macro_f1 0.6996
2026-09-25 19:31:57,401 INFO   ep 068 loss 0.1595 val_macro_f1 0.7028
2026-09-25 19:31:57,759 INFO   ep 069 loss 0.2867 val_macro_f1 0.7072 *
2026-09-25 19:31:58,130 INFO   ep 070 loss 0.3112 val_macro_f1 0.7007
2026-09-25 19:31:58,491 INFO   ep 071 loss 0.3132 val_macro_f1 0.6943
2026-09-25 19:31:58,860 INFO   ep 072 loss 0.3118 val_macro_f1 0.6954
2026-09-25 19:31:59,226 INFO   ep 073 loss 0.3100 val_macro_f1 0.7013
2026-09-25 19:31:59,615 INFO   ep 074 loss 0.2429 val_macro_f1 0.6987
2026-09-25 19:31:59,965 INFO   ep 075 loss 0.1422 val_macro_f1 0.7037
2026-09-25 19:32:00,328 INFO   ep 076 loss 0.2253 val_macro_f1 0.7058
2026-09-25 19:32:00,679 INFO   ep 077 loss 0.1537 val_macro_f1 0.7061
2026-09-25 19:32:01,026 INFO   ep 078 loss 0.2065 val_macro_f1 0.7017
2026-09-25 19:32:01,377 INFO   ep 079 loss 0.1738 val_macro_f1 0.7042
2026-09-25 19:32:01,750 INFO   ep 080 loss 0.2887 val_macro_f1 0.7087 *
2026-09-25 19:32:02,119 INFO   ep 081 loss 0.3141 val_macro_f1 0.7090 *
2026-09-25 19:32:02,504 INFO   ep 082 loss 0.2331 val_macro_f1 0.7028
2026-09-25 19:32:02,866 INFO   ep 083 loss 0.2173 val_macro_f1 0.7086
2026-09-25 19:32:03,245 INFO   ep 084 loss 0.2327 val_macro_f1 0.7055
2026-09-25 19:32:03,630 INFO   ep 085 loss 0.2309 val_macro_f1 0.7106 *
2026-09-25 19:32:03,977 INFO   ep 086 loss 0.1934 val_macro_f1 0.7084
2026-09-25 19:32:04,318 INFO   ep 087 loss 0.1631 val_macro_f1 0.7076
2026-09-25 19:32:04,697 INFO   ep 088 loss 0.1188 val_macro_f1 0.7070
2026-09-25 19:32:05,074 INFO   ep 089 loss 0.1565 val_macro_f1 0.7116 *
2026-09-25 19:32:05,449 INFO   ep 090 loss 0.1645 val_macro_f1 0.7100
2026-09-25 19:32:05,823 INFO   ep 091 loss 0.2245 val_macro_f1 0.7081
2026-09-25 19:32:06,177 INFO   ep 092 loss 0.3345 val_macro_f1 0.7096
2026-09-25 19:32:06,522 INFO   ep 093 loss 0.2287 val_macro_f1 0.7109
2026-09-25 19:32:06,880 INFO   ep 094 loss 0.2520 val_macro_f1 0.7103
2026-09-25 19:32:07,246 INFO   ep 095 loss 0.1958 val_macro_f1 0.7053
2026-09-25 19:32:07,619 INFO   ep 096 loss 0.1469 val_macro_f1 0.7056
2026-09-25 19:32:07,990 INFO   ep 097 loss 0.2435 val_macro_f1 0.7089
2026-09-25 19:32:08,373 INFO   ep 098 loss 0.3191 val_macro_f1 0.7115
2026-09-25 19:32:08,741 INFO   ep 099 loss 0.2149 val_macro_f1 0.7086
2026-09-25 19:32:09,091 INFO   ep 100 loss 0.1504 val_macro_f1 0.7096
2026-09-25 19:32:09,457 INFO   ep 101 loss 0.1823 val_macro_f1 0.7076
2026-09-25 19:32:09,839 INFO   ep 102 loss 0.1680 val_macro_f1 0.7082
2026-09-25 19:32:10,208 INFO   ep 103 loss 0.2253 val_macro_f1 0.7087
2026-09-25 19:32:10,586 INFO   ep 104 loss 0.1082 val_macro_f1 0.7077
2026-09-25 19:32:10,948 INFO   ep 105 loss 0.1510 val_macro_f1 0.7078
2026-09-25 19:32:11,305 INFO   ep 106 loss 0.1884 val_macro_f1 0.7082
2026-09-25 19:32:11,655 INFO   ep 107 loss 0.2278 val_macro_f1 0.7073
2026-09-25 19:32:12,017 INFO   ep 108 loss 0.2451 val_macro_f1 0.7072
2026-09-25 19:32:12,385 INFO   ep 109 loss 0.1438 val_macro_f1 0.7079
2026-09-25 19:32:12,750 INFO   ep 110 loss 0.1441 val_macro_f1 0.7100
2026-09-25 19:32:13,102 INFO   ep 111 loss 0.2149 val_macro_f1 0.7079
2026-09-25 19:32:13,452 INFO   ep 112 loss 0.1624 val_macro_f1 0.7080
2026-09-25 19:32:13,820 INFO   ep 113 loss 0.1098 val_macro_f1 0.7086
2026-09-25 19:32:14,177 INFO   ep 114 loss 0.1523 val_macro_f1 0.7091
2026-09-25 19:32:14,513 INFO   ep 115 loss 0.1137 val_macro_f1 0.7085
2026-09-25 19:32:14,861 INFO   ep 116 loss 0.1834 val_macro_f1 0.7090
2026-09-25 19:32:15,189 INFO   ep 117 loss 0.1250 val_macro_f1 0.7083
2026-09-25 19:32:15,544 INFO   ep 118 loss 0.1426 val_macro_f1 0.7088
2026-09-25 19:32:15,911 INFO   ep 119 loss 0.1368 val_macro_f1 0.7088
2026-09-25 19:32:15,955 INFO no-opcode LGC       seed0 macro_f1=0.6825 macro_auc=0.8768
2026-09-25 19:32:16,311 INFO   ep 000 loss 3.9472 val_macro_f1 0.0967 *
2026-09-25 19:32:16,656 INFO   ep 001 loss 1.4916 val_macro_f1 0.2393 *
2026-09-25 19:32:16,991 INFO   ep 002 loss 2.3839 val_macro_f1 0.3468 *
2026-09-25 19:32:17,334 INFO   ep 003 loss 1.2029 val_macro_f1 0.4143 *
2026-09-25 19:32:17,662 INFO   ep 004 loss 0.7874 val_macro_f1 0.4116
2026-09-25 19:32:17,989 INFO   ep 005 loss 1.1149 val_macro_f1 0.3846
2026-09-25 19:32:18,321 INFO   ep 006 loss 0.9802 val_macro_f1 0.4737 *
2026-09-25 19:32:18,663 INFO   ep 007 loss 0.8679 val_macro_f1 0.5238 *
2026-09-25 19:32:19,009 INFO   ep 008 loss 1.1423 val_macro_f1 0.5229
2026-09-25 19:32:19,355 INFO   ep 009 loss 1.0273 val_macro_f1 0.4433
2026-09-25 19:32:19,723 INFO   ep 010 loss 1.4956 val_macro_f1 0.5006
2026-09-25 19:32:20,063 INFO   ep 011 loss 1.1598 val_macro_f1 0.5459 *
2026-09-25 19:32:20,395 INFO   ep 012 loss 0.8326 val_macro_f1 0.5140
2026-09-25 19:32:20,734 INFO   ep 013 loss 0.7716 val_macro_f1 0.5219
2026-09-25 19:32:21,058 INFO   ep 014 loss 0.7896 val_macro_f1 0.4922
2026-09-25 19:32:21,383 INFO   ep 015 loss 1.1559 val_macro_f1 0.5600 *
2026-09-25 19:32:21,731 INFO   ep 016 loss 0.5193 val_macro_f1 0.5542
2026-09-25 19:32:22,073 INFO   ep 017 loss 0.6928 val_macro_f1 0.5651 *
2026-09-25 19:32:22,421 INFO   ep 018 loss 1.2128 val_macro_f1 0.4688
2026-09-25 19:32:22,741 INFO   ep 019 loss 1.2081 val_macro_f1 0.5825 *
2026-09-25 19:32:23,060 INFO   ep 020 loss 0.7435 val_macro_f1 0.4548
2026-09-25 19:32:23,395 INFO   ep 021 loss 0.6715 val_macro_f1 0.6083 *
2026-09-25 19:32:23,766 INFO   ep 022 loss 0.5981 val_macro_f1 0.5758
2026-09-25 19:32:24,123 INFO   ep 023 loss 1.3494 val_macro_f1 0.5577
2026-09-25 19:32:24,510 INFO   ep 024 loss 0.7303 val_macro_f1 0.6347 *
2026-09-25 19:32:24,860 INFO   ep 025 loss 0.8784 val_macro_f1 0.5781
2026-09-25 19:32:25,224 INFO   ep 026 loss 1.1005 val_macro_f1 0.6120
2026-09-25 19:32:25,598 INFO   ep 027 loss 0.9269 val_macro_f1 0.6384 *
2026-09-25 19:32:25,954 INFO   ep 028 loss 0.4575 val_macro_f1 0.6436 *
2026-09-25 19:32:26,277 INFO   ep 029 loss 0.5050 val_macro_f1 0.6311
2026-09-25 19:32:26,624 INFO   ep 030 loss 0.5244 val_macro_f1 0.6386
2026-09-25 19:32:26,956 INFO   ep 031 loss 0.5006 val_macro_f1 0.6726 *
2026-09-25 19:32:27,273 INFO   ep 032 loss 0.6439 val_macro_f1 0.6670
2026-09-25 19:32:27,621 INFO   ep 033 loss 0.7730 val_macro_f1 0.6631
2026-09-25 19:32:27,970 INFO   ep 034 loss 0.8158 val_macro_f1 0.6768 *
2026-09-25 19:32:28,313 INFO   ep 035 loss 0.4476 val_macro_f1 0.6812 *
2026-09-25 19:32:28,696 INFO   ep 036 loss 0.4770 val_macro_f1 0.6603
2026-09-25 19:32:29,069 INFO   ep 037 loss 0.4263 val_macro_f1 0.6474
2026-09-25 19:32:29,431 INFO   ep 038 loss 0.4941 val_macro_f1 0.6246
2026-09-25 19:32:29,816 INFO   ep 039 loss 0.4483 val_macro_f1 0.6844 *
2026-09-25 19:32:30,164 INFO   ep 040 loss 0.4861 val_macro_f1 0.6912 *
2026-09-25 19:32:30,513 INFO   ep 041 loss 0.5898 val_macro_f1 0.6628
2026-09-25 19:32:30,856 INFO   ep 042 loss 0.5636 val_macro_f1 0.6799
2026-09-25 19:32:31,194 INFO   ep 043 loss 0.4858 val_macro_f1 0.6952 *
2026-09-25 19:32:31,541 INFO   ep 044 loss 0.3399 val_macro_f1 0.6937
2026-09-25 19:32:31,887 INFO   ep 045 loss 0.3610 val_macro_f1 0.6868
2026-09-25 19:32:32,225 INFO   ep 046 loss 0.4827 val_macro_f1 0.6899
2026-09-25 19:32:32,564 INFO   ep 047 loss 0.3769 val_macro_f1 0.6920
2026-09-25 19:32:32,893 INFO   ep 048 loss 0.2863 val_macro_f1 0.6863
2026-09-25 19:32:33,215 INFO   ep 049 loss 0.4243 val_macro_f1 0.6937
2026-09-25 19:32:33,571 INFO   ep 050 loss 0.2132 val_macro_f1 0.6803
2026-09-25 19:32:33,926 INFO   ep 051 loss 0.8280 val_macro_f1 0.6935
2026-09-25 19:32:34,285 INFO   ep 052 loss 0.2477 val_macro_f1 0.6830
2026-09-25 19:32:34,648 INFO   ep 053 loss 0.3979 val_macro_f1 0.6966 *
2026-09-25 19:32:34,993 INFO   ep 054 loss 0.2816 val_macro_f1 0.6821
2026-09-25 19:32:35,332 INFO   ep 055 loss 0.2566 val_macro_f1 0.7016 *
2026-09-25 19:32:35,683 INFO   ep 056 loss 0.1998 val_macro_f1 0.6979
2026-09-25 19:32:36,030 INFO   ep 057 loss 0.4764 val_macro_f1 0.7024 *
2026-09-25 19:32:36,362 INFO   ep 058 loss 0.2895 val_macro_f1 0.6976
2026-09-25 19:32:36,698 INFO   ep 059 loss 0.2244 val_macro_f1 0.6963
2026-09-25 19:32:37,040 INFO   ep 060 loss 0.2488 val_macro_f1 0.7071 *
2026-09-25 19:32:37,382 INFO   ep 061 loss 0.1656 val_macro_f1 0.6889
2026-09-25 19:32:37,730 INFO   ep 062 loss 0.2374 val_macro_f1 0.7017
2026-09-25 19:32:38,071 INFO   ep 063 loss 0.2192 val_macro_f1 0.7037
2026-09-25 19:32:38,414 INFO   ep 064 loss 0.2933 val_macro_f1 0.7085 *
2026-09-25 19:32:38,754 INFO   ep 065 loss 0.2083 val_macro_f1 0.7006
2026-09-25 19:32:39,077 INFO   ep 066 loss 0.3286 val_macro_f1 0.7037
2026-09-25 19:32:39,395 INFO   ep 067 loss 0.1892 val_macro_f1 0.7041
2026-09-25 19:32:39,774 INFO   ep 068 loss 0.1466 val_macro_f1 0.7062
2026-09-25 19:32:40,107 INFO   ep 069 loss 0.2829 val_macro_f1 0.7085 *
2026-09-25 19:32:40,443 INFO   ep 070 loss 0.3172 val_macro_f1 0.7061
2026-09-25 19:32:40,780 INFO   ep 071 loss 0.2695 val_macro_f1 0.7053
2026-09-25 19:32:41,110 INFO   ep 072 loss 0.3013 val_macro_f1 0.7096 *
2026-09-25 19:32:41,437 INFO   ep 073 loss 0.2535 val_macro_f1 0.7007
2026-09-25 19:32:41,794 INFO   ep 074 loss 0.2372 val_macro_f1 0.6944
2026-09-25 19:32:42,119 INFO   ep 075 loss 0.1380 val_macro_f1 0.7058
2026-09-25 19:32:42,455 INFO   ep 076 loss 0.2251 val_macro_f1 0.7017
2026-09-25 19:32:42,797 INFO   ep 077 loss 0.1594 val_macro_f1 0.7100 *
2026-09-25 19:32:43,121 INFO   ep 078 loss 0.1114 val_macro_f1 0.7112 *
2026-09-25 19:32:43,466 INFO   ep 079 loss 0.1923 val_macro_f1 0.7008
2026-09-25 19:32:43,820 INFO   ep 080 loss 0.2658 val_macro_f1 0.7059
2026-09-25 19:32:44,152 INFO   ep 081 loss 0.3208 val_macro_f1 0.7151 *
2026-09-25 19:32:44,480 INFO   ep 082 loss 0.1878 val_macro_f1 0.7069
2026-09-25 19:32:44,818 INFO   ep 083 loss 0.2239 val_macro_f1 0.7091
2026-09-25 19:32:45,152 INFO   ep 084 loss 0.1667 val_macro_f1 0.7091
2026-09-25 19:32:45,491 INFO   ep 085 loss 0.2240 val_macro_f1 0.7117
2026-09-25 19:32:45,835 INFO   ep 086 loss 0.1586 val_macro_f1 0.7096
2026-09-25 19:32:46,163 INFO   ep 087 loss 0.1958 val_macro_f1 0.7104
2026-09-25 19:32:46,503 INFO   ep 088 loss 0.1054 val_macro_f1 0.7083
2026-09-25 19:32:46,825 INFO   ep 089 loss 0.1073 val_macro_f1 0.7070
2026-09-25 19:32:47,139 INFO   ep 090 loss 0.1340 val_macro_f1 0.7055
2026-09-25 19:32:47,461 INFO   ep 091 loss 0.2049 val_macro_f1 0.7057
2026-09-25 19:32:47,777 INFO   ep 092 loss 0.2541 val_macro_f1 0.7075
2026-09-25 19:32:48,103 INFO   ep 093 loss 0.2169 val_macro_f1 0.7062
2026-09-25 19:32:48,430 INFO   ep 094 loss 0.2276 val_macro_f1 0.7074
2026-09-25 19:32:48,776 INFO   ep 095 loss 0.1455 val_macro_f1 0.7076
2026-09-25 19:32:49,140 INFO   ep 096 loss 0.1327 val_macro_f1 0.7069
2026-09-25 19:32:49,500 INFO   ep 097 loss 0.1996 val_macro_f1 0.7081
2026-09-25 19:32:49,846 INFO   ep 098 loss 0.2300 val_macro_f1 0.7057
2026-09-25 19:32:50,169 INFO   ep 099 loss 0.2821 val_macro_f1 0.7080
2026-09-25 19:32:50,516 INFO   ep 100 loss 0.0993 val_macro_f1 0.7070
2026-09-25 19:32:50,839 INFO   ep 101 loss 0.1799 val_macro_f1 0.7058
2026-09-25 19:32:51,172 INFO   ep 102 loss 0.1177 val_macro_f1 0.7047
2026-09-25 19:32:51,506 INFO   ep 103 loss 0.1724 val_macro_f1 0.7058
2026-09-25 19:32:51,860 INFO   ep 104 loss 0.1566 val_macro_f1 0.7043
2026-09-25 19:32:52,216 INFO   ep 105 loss 0.1267 val_macro_f1 0.7050
2026-09-25 19:32:52,555 INFO   ep 106 loss 0.1814 val_macro_f1 0.7054
2026-09-25 19:32:52,889 INFO   ep 107 loss 0.2072 val_macro_f1 0.7047
2026-09-25 19:32:53,237 INFO   ep 108 loss 0.2165 val_macro_f1 0.7038
2026-09-25 19:32:53,604 INFO   ep 109 loss 0.0986 val_macro_f1 0.7040
2026-09-25 19:32:53,984 INFO   ep 110 loss 0.1155 val_macro_f1 0.7041
2026-09-25 19:32:54,359 INFO   ep 111 loss 0.2386 val_macro_f1 0.7041
2026-09-25 19:32:54,703 INFO   ep 112 loss 0.1372 val_macro_f1 0.7036
2026-09-25 19:32:55,068 INFO   ep 113 loss 0.1147 val_macro_f1 0.7039
2026-09-25 19:32:55,427 INFO   ep 114 loss 0.1297 val_macro_f1 0.7035
2026-09-25 19:32:55,784 INFO   ep 115 loss 0.0852 val_macro_f1 0.7036
2026-09-25 19:32:56,130 INFO   ep 116 loss 0.1658 val_macro_f1 0.7036
2026-09-25 19:32:56,473 INFO   ep 117 loss 0.1281 val_macro_f1 0.7037
2026-09-25 19:32:56,817 INFO   ep 118 loss 0.0848 val_macro_f1 0.7038
2026-09-25 19:32:57,141 INFO   ep 119 loss 0.1458 val_macro_f1 0.7038
2026-09-25 19:32:57,178 INFO no-opcode LGC       seed1 macro_f1=0.6932 macro_auc=0.8780
2026-09-25 19:32:57,564 INFO   ep 000 loss 4.0449 val_macro_f1 0.0317 *
2026-09-25 19:32:57,947 INFO   ep 001 loss 1.4659 val_macro_f1 0.4223 *
2026-09-25 19:32:58,308 INFO   ep 002 loss 2.4871 val_macro_f1 0.2548
2026-09-25 19:32:58,654 INFO   ep 003 loss 1.0851 val_macro_f1 0.4963 *
2026-09-25 19:32:59,014 INFO   ep 004 loss 0.9554 val_macro_f1 0.3880
2026-09-25 19:32:59,383 INFO   ep 005 loss 1.3733 val_macro_f1 0.3559
2026-09-25 19:32:59,759 INFO   ep 006 loss 0.9637 val_macro_f1 0.4245
2026-09-25 19:33:00,080 INFO   ep 007 loss 0.8282 val_macro_f1 0.4894
2026-09-25 19:33:00,416 INFO   ep 008 loss 1.0814 val_macro_f1 0.4852
2026-09-25 19:33:00,749 INFO   ep 009 loss 1.2108 val_macro_f1 0.5536 *
2026-09-25 19:33:01,082 INFO   ep 010 loss 2.6321 val_macro_f1 0.4875
2026-09-25 19:33:01,436 INFO   ep 011 loss 1.1709 val_macro_f1 0.5764 *
2026-09-25 19:33:01,788 INFO   ep 012 loss 0.7664 val_macro_f1 0.4988
2026-09-25 19:33:02,152 INFO   ep 013 loss 0.8326 val_macro_f1 0.5497
2026-09-25 19:33:02,497 INFO   ep 014 loss 0.7785 val_macro_f1 0.5293
2026-09-25 19:33:02,828 INFO   ep 015 loss 1.1018 val_macro_f1 0.4826
2026-09-25 19:33:03,208 INFO   ep 016 loss 0.4601 val_macro_f1 0.4957
2026-09-25 19:33:03,579 INFO   ep 017 loss 0.7125 val_macro_f1 0.4895
2026-09-25 19:33:03,928 INFO   ep 018 loss 0.9739 val_macro_f1 0.5679
2026-09-25 19:33:04,274 INFO   ep 019 loss 0.8916 val_macro_f1 0.5874 *
2026-09-25 19:33:04,636 INFO   ep 020 loss 0.8612 val_macro_f1 0.5954 *
2026-09-25 19:33:04,981 INFO   ep 021 loss 0.6884 val_macro_f1 0.6139 *
2026-09-25 19:33:05,328 INFO   ep 022 loss 0.6176 val_macro_f1 0.5984
2026-09-25 19:33:05,675 INFO   ep 023 loss 1.7426 val_macro_f1 0.5855
2026-09-25 19:33:06,038 INFO   ep 024 loss 0.8840 val_macro_f1 0.6233 *
2026-09-25 19:33:06,409 INFO   ep 025 loss 0.9038 val_macro_f1 0.6229
2026-09-25 19:33:06,783 INFO   ep 026 loss 0.8351 val_macro_f1 0.6285 *
2026-09-25 19:33:07,138 INFO   ep 027 loss 1.0310 val_macro_f1 0.6430 *
2026-09-25 19:33:07,524 INFO   ep 028 loss 0.3967 val_macro_f1 0.6449 *
2026-09-25 19:33:07,891 INFO   ep 029 loss 0.4363 val_macro_f1 0.6234
2026-09-25 19:33:08,244 INFO   ep 030 loss 0.5272 val_macro_f1 0.6475 *
2026-09-25 19:33:08,578 INFO   ep 031 loss 0.4035 val_macro_f1 0.6345
2026-09-25 19:33:08,912 INFO   ep 032 loss 0.6632 val_macro_f1 0.6190
2026-09-25 19:33:09,261 INFO   ep 033 loss 0.7939 val_macro_f1 0.6672 *
2026-09-25 19:33:09,652 INFO   ep 034 loss 0.7104 val_macro_f1 0.6457